### ISSUE TITLE
[MANAGER] Cargo (rust)

### ISSUE THREAD

**Issue by ROMUSKING** [marticliment/UniGetUI#1124]
Since new release adds pypi and node package support, maybe you can consider adding rust's cargo crates. Using cargo binstall finds available binaries and downloads them instead of compiling from source.  Perhaps it can be used without installing the entire toolchain?

**Comment by TieWay59** [comment]
`cargo binstall` is quite different, but still wish to see a version of  [WingetUI](https://github.com/marticliment/WingetUI) add basic Cargo support. ❤
