### ISSUE TITLE
[BUG/ISSUE] incorrect icon and screenshot for same pkg name in multiple sources

### ISSUE THREAD

**Issue by ppvnf** [marticliment/UniGetUI#1154]
<s> I am unable to share the link/import this scoop (games/ares) package properly because WingetUI confuses it with a npm package
[Pacotes.txt](https://github.com/marticliment/WingetUI/files/11829627/Pacotes.txt)
</s>

https://marticliment.com/wingetui/share/?pid=ares&pname=Ares
the img and logo are incorrect, but I am not sure how to fix it since there is a chocolatey package with the same name:
![favicon](https://github.com/marticliment/WingetUI/assets/73800734/0f23d6f2-0f1b-4a1f-b6a0-9f833ced6722)
![famicom_gimmick](https://github.com/marticliment/WingetUI/assets/73800734/bf8d84c4-6bb2-40a7-8177-d7e1b2f56b69)

**Comment by ppvnf** [comment]
the only thing left to fix is enabling different icon/screenshots for packages with same name but different sources, right?

**Comment by marticliment** [comment]
i think so, but this will be tricky, because one of the main benefits of shared icons is their intercompatiblilty, otherwise much less packages would have icons

**Comment by ppvnf** [comment]
yes, I think shared icons/screenshots should be used as fallback in case no icons or screenshots are provided for a source

**Comment by marticliment** [comment]
Update: As of 3.2.1, adding an icon with the id being `ManagerName.ExactPackageId` will target a specific package from a specific package manager
