### ISSUE TITLE
[FEATURE REQUEST] Ability to see how a package is being installed [badges to installer widgets]

### ISSUE THREAD

**Issue by c010rb1indusa** [marticliment/UniGetUI#1205]
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This proposal is a completely new feature. If you want to suggest an improvement or an enhancement, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=enhancement&projects=&template=enhancement-improvement.yml&title=%5BENHANCEMENT%5D+%28Enter+your+description+here%29)

### Describe the new feature

First of all I just want to say thank you. This is the best GUI for winget I've used, and the other integrations just make it top notch. Not to mention it's also gorgeous.

1. Would like visual confirmation that a package is being installed as admin, is interactive or hash check will be skipped etc. w/o having to go into said packages' details menu. A column for each of those options with a selectable check mark to enable/disable said option would be much easier than the current way of enabling those options as well as seeing those options for many packages at a glance.  Also Perhaps if [custom install locations](https://github.com/marticliment/WingetUI/issues/1036) is implemented a dropdown file browser could be implemented instead of the checkbox for 'install as admin'.  Or perhaps a cleaner and safer way of doing this is having custom folder locations saved as presets instead of an entire filesystem but that's getting off topic.

2. In addition to my first request, would also like to see additional columns for other information that exists in the package details menu, i.e Homepage, Publisher, Author, Installer URL etc. They don't have to be enabled by default but it would be nice if they were were available via a right click to enable.

3. And would like to be able to resize said columns and sort them in w/e order the user wishes.

Thank you again for all your hard work. I haven't found a tool that saves me this much time w/o having to deal with the CLI in years. Best of luck with it all!

### Describe how this new feature could help users.

Easier way to enable options for packages as well as see what options are enabled for all packages at a glance. And would allow for columns that can be sorted and resized as well as additional columns that can be enabled to display additional package info like homepage, publisher, author and installer url.

**Comment by marticliment** [comment]
Hello,

> * In addition to my first request, would also like to see additional columns for other information that exists in the package details menu, i.e Homepage, Publisher, Author, Installer URL etc. They don't have to be enabled by default but it would be nice if they were were available via a right click to enable.
> *

this feature is not doable, since Package Managers do not provide this information in ways that are efficient enough to bulk-load them.



> * Would like visual confirmation that a package is being installed as admin, is interactive or hash check will be skipped etc. w/o having to go into said packages' details menu. A column for each of those options with a selectable check mark to enable/disable said option would be much easier than the current way of enabling those options as well as seeing those options for many packages at a glance.  Also Perhaps if [custom install locations](https://github.com/marticliment/WingetUI/issues/1036) is implemented a dropdown file browser could be implemented instead of the checkbox for 'install as admin'.  Or perhaps a cleaner and safer way of doing this is having custom folder locations saved as presets instead of an entire filesystem but that's getting off topic.
> *

This might be doable
