### ISSUE TITLE
[ENHANCEMENT] allow updates context menu

### ISSUE THREAD

**Issue by ppvnf** [marticliment/UniGetUI#1374]
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This improvements refers to an existing feature. If you want to suggest a new feature, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=new-feature&projects=&template=feature-request.yml&title=%5BFEATURE+REQUEST%5D+%28Enter+your+description+here%29)
- [X] This improvements is not a bug. If you want to report a bug, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=bug&projects=&template=bug-issue.yml&title=%5BBUG%5D+%28Enter+your+description+here%29)

### Describe the improvement

similar to https://github.com/marticliment/WingetUI/issues/936, but for the context menu. I think that when the package is already blacklisted the context menu 'ignore updates' option should be changed to something like 'allow updates':

<img width="659" alt="Screenshot 2023-09-19 103824" src="https://github.com/marticliment/WingetUI/assets/73800734/cd2e9318-57d7-470a-88cc-518fa72b90de">

### Describe how this improvement could help users.

makes it easier to unblock updates

**Comment by mrixner** [comment]
Fixed in 0e2e782
