### ISSUE TITLE
[ENHANCEMENT] Add "Go to install location" button in rightclick + show the path of installation

### ISSUE THREAD

**Issue by A7exSchin** [marticliment/UniGetUI#1386]
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This improvements refers to an existing feature. If you want to suggest a new feature, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=new-feature&projects=&template=feature-request.yml&title=%5BFEATURE+REQUEST%5D+%28Enter+your+description+here%29)
- [X] This improvements is not a bug. If you want to report a bug, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=bug&projects=&template=bug-issue.yml&title=%5BBUG%5D+%28Enter+your+description+here%29)

### Describe the improvement

Add a single menu item to the right click menu of installed software, that lets me go to the respective directory the software is isntalled in.

If this is not possible, alternatively it would be helpful to document the installation path in the FAQ for various sources.

### Describe how this improvement could help users.

Right now it is very troublesome to find the location, where stuff is installed. For example installing maven via chocolatey results in the path `C:\Users\User\AppData\Local\Programs\WingetUI\choco-cli\lib`. But this path is already different when installing stuff via winget.

Adding the menu item improves fluidity and streamlines workflow.

**Comment by A7exSchin** [comment]
Would be a possible temporary fix for #1036

**Comment by A7exSchin** [comment]
@marticliment thanks for the quick answer! I just realized that "Go to Source" is a bit misleading. More like a "Go to Install Location".

**Comment by ppvnf** [comment]
For Winget there is an open issue about this https://github.com/microsoft/winget-cli/issues/2298

**Comment by LittleFreak** [comment]
Its actually quite important, since not all Apps are shown in the Start menu or windows search after the installation.
(I'm looking at you QEMU,...)
