### ISSUE TITLE
[ENHANCEMENT] Option for Notifications: Notification on new update found

### ISSUE THREAD

**Issue by svharsdorf** [marticliment/UniGetUI#1443]
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This improvements refers to an existing feature. If you want to suggest a new feature, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=new-feature&projects=&template=feature-request.yml&title=%5BFEATURE+REQUEST%5D+%28Enter+your+description+here%29)
- [X] This improvements is not a bug. If you want to report a bug, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=bug&projects=&template=bug-issue.yml&title=%5BBUG%5D+%28Enter+your+description+here%29)

### Describe the improvement

Currently there is an option to notify when updates are available.
But the option keeps pushing a notification every time it checks for updates and reports with updates are available.
This happens even when there are no new-found packages since the last update check and pushed notification.
Example:
1pm - 1 Update available (Thunderbird 1.17 -> 1.18)
2pm - 1 Update available (Thunderbird 1.17 -> 1.18)
3pm - 1 Update available (Thunderbird 1.17 -> 1.18)
...etc...

Ideally, this option should only send out a notification for new updates when there are new updates found that haven't already been discovered before and notified about.

### Describe how this improvement could help users.

No user needs several notifications about the same available update(s).
It only makes sense to notify the user about new updates that they weren't already notified about.
As of right now, the user gets barraged with notifications (they in most cases already know about) until they either turn off the notification option or they clear the software update tab.

**Comment by DipsoNOR** [comment]
This is pretty annoying. Having like 30+ notifications in the actions center after leaving the computer on for a night is just silly.
Setting the interval for notifications and having a bit more smart handling of this would make it a lot less irritating to have notifications turned on for updates.

**Comment by kriswilk** [comment]
I replied in #2061 before finding this issue, which is more specifically what I'm bothered by. Like @DipsoNOR, I find it really frustrating to wake up to dozens of notifications for the same package update(s). It's also annoying to dismiss a notification while I'm working and to have it reappear every hour later.
