### ISSUE TITLE
[FEATURE REQUEST] Consider displaying package update options for ignored updates

### ISSUE THREAD

**Issue by fossbrandon** [marticliment/UniGetUI#1475]
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This improvements refers to an existing feature. If you want to suggest a new feature, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=new-feature&projects=&template=feature-request.yml&title=%5BFEATURE+REQUEST%5D+%28Enter+your+description+here%29)
- [X] This improvements is not a bug. If you want to report a bug, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=bug&projects=&template=bug-issue.yml&title=%5BBUG%5D+%28Enter+your+description+here%29)

### Describe the improvement

There are certain packages that I like to update in a special way outside of how winget or other package managers prefer to upgrade them. To prevent wingetui from attempting to upgrade these packages, I currently use the `Ignore selected packages` option. However, this makes it so that I can't view when updates are available for these packages. I think it would be nice to add an additional list of packages that aren't ignored, but they also aren't able to be upgraded automatically via wingetui. Essentially, you would have the list of available package updates with the option to update (already exists), a list of ignored packages that you don't care to update or even want to see if an upgrade is available (already exists as ignored packages), and then a new list of packages that you don't want wingetui to update, but you would like it to still show that an update is available so that I can go and perform those updates manually my own way.

Design considerations: A user could select packages for this new category and then click a new button like `Don't automatically update selected packages`. Then, you could potentially have a collapsible list of these packages under the existing package updates where a user could expand the list and see available updates for packages in this category, but not have the option to automatically perform the update.

### Describe how this improvement could help users.

This would help users who have packages they want to see available updates for, but don't want wingetui to handle the updates.

**Comment by ppvnf** [comment]
similar to https://github.com/marticliment/WingetUI/issues/1383, but this issue describe useful details I think

**Comment by marticliment** [comment]
Yes, they are the same feature but opposite

**Comment by csoltenborn** [comment]
I wanted to suggest something similar. My issue is that some packages can apparently not be updated by WingetUI (they always fail), but updating them through their "own" mechanism works just nice. I would like to be able to mark such packages as "Manual update", resulting in WingetUI not trying to update them, but still telling me that updates are available (such that I can then manually update them). If I ignore the packages, I will not get the "Update!" reminders... Hopes that this makes sense :-)

And, btw, thanks for the great project!

**Comment by mrixner** [comment]
Would adding the current version and available version of a package to the ignored updates dialog work (see #2957  & #974), or were you hoping for something more blatant?
If the former, I've added this in #2987.

**Comment by fossbrandon** [comment]
Your changes totally work for what I was looking for. Long term it could make sense to separate the ignored packages from ones you want to upgrade manually to keep the stuff you care about in its own easy to see section, but that also adds complexity that isn't really needed. Thanks for contributing those changes!

This story can be closed unless anyone else feels like having separate lists would be beneficial.
