### ISSUE TITLE
[ENHANCEMENT] Allow Changing of the Powershell Executable

### ISSUE THREAD

**Issue by JAK1047** [marticliment/UniGetUI#1650]
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This improvements refers to an existing feature. If you want to suggest a new feature, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=new-feature&projects=&template=feature-request.yml&title=%5BFEATURE+REQUEST%5D+%28Enter+your+description+here%29)
- [X] This improvements is not a bug. If you want to report a bug, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=bug&projects=&template=bug-issue.yml&title=%5BBUG%5D+%28Enter+your+description+here%29)

### Describe the improvement

Would it be possible to have the option to change the executable of Powershell being used by WingetUI Powershell Package Manager to the current releases? 7.4, 7.3, etc. With pwsh.exe if you install modules under the AllUsers scope they install to C:\Program Files\PowerShell\Modules instead and aren't picked up by Windows Powershell. The only real update would be that the Test-GalleryModuleUpdate function would need to be changed as the MaximumRedirect parameter was modified in Powershell Core to return a terminating error (assumedly you could just swap to using Find-Module to return the latest version available).

### Describe how this improvement could help users.

Many like myself only use the current releases of Powershell.

**Comment by eizedev** [comment]
That would be a great addition!

**Comment by kplantus** [comment]
This was my major reason for downloading WingetUI -- helping manage updates to my Pwsh modules.  Unfortunately, I only use pwsh core.
Replacing powershell.exe with pwsh.exe DOES provide the desired behavior within WingetUI -- but it's not recommended to completely replace the Windows PowerShell executable because a few things still require use within Windows Powershell.
