### ISSUE TITLE
App icons before packages

### ISSUE THREAD

**Issue by maicol07** [marticliment/UniGetUI#171]
Show the app icon when possible in the app list

**Comment by martinet101** [comment]
neither winget or scoop provide this functionality

**Comment by ppvnf** [comment]
@martinet101 https://winstall.app somehow manages to do add icons to Winget packages

**Comment by martinet101** [comment]
They appear to be propietary, since minor apps don't have icon

![image](https://user-images.githubusercontent.com/53119851/193409917-b3fd355c-92a9-450e-93e7-19ea52e191e3.png)

**Comment by ppvnf** [comment]
I just found out that they are an open-source project:
https://github.com/MehediH/winstall/blob/master/components/AppIcon.js
https://github.com/MehediH/winstall/blob/master/data/popularApps.json

**Comment by martinet101** [comment]
That could well be a possible thing...

**Comment by martinet101** [comment]
The retrieval could be heuristic, the most similar entry (if one) will be the icon

**Comment by martinet101** [comment]
The icons have been added to the about section.

Regarding the package lists, the feature is still under study.

(Preview of the about section:)
![image](https://user-images.githubusercontent.com/53119851/196528358-f1fa0f83-5eeb-463a-ab04-8b354448506a.png)

**Comment by marticliment** [comment]
Icons won't be added to the package list due to the hugr amount of packages, and the impact on performance that this would have.

They will still remain on the info window, however.

**Comment by ppvnf** [comment]
How about making icons visible on the pkg list when hovering/clicking on a certain package?

**Comment by marticliment** [comment]
it would look disordered. I have tested that on other applications, and it doesn't look good.

**Comment by marticliment** [comment]
They say it is better late than never...

Icons will be available (altough not enabled by default) on the next stable release
![image](https://github.com/user-attachments/assets/59f50ce6-0fc0-4444-8d0a-3b8ab5cf00a4)
