### ISSUE TITLE
[BUG] Environment variables are not updated unless WingetUI is restarted

### ISSUE THREAD

**Issue by Wallby** [marticliment/UniGetUI#1846]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

With WingetUI running, I added the environment variablers RUSTUP_HOME and CARGO_HOME, and then I tried to install Rustlang.Rustup interactively.

This installer opens a cmd.exe window and outputs the paths used.
I tried to cancel and then restart the installation, but this didn't work.
The only way for the new environment variables to be detected was to close WingetUI entirely and then restart it.

### Steps to reproduce the issue

1. open WingetUI
2. go to "Edit the system environment variables"
3. add RUSTUP_HOME and CARGO_HOME and set each to a value different than then default
4. try to interactively install Rustlang.Rustup from WingetUI, and now after `Rustup metadata and toolchains will be installed into the Rustup home directory, located at:` there was the default value
5. restart WingetUI
6. try to interactively install Rustlang.Rustup from WingetUI again, and now after `Rustup metadata and toolchains will be installed into the Rustup home directory, located at:` there was the new value

### WingetUI Log

```text
Doesn't seem applicable
```

### Package Managers Logs

```text
Doesn't seem applicable
```

### Relevant information

Tested using WingetUI 2.2.0 (i.e. the latest stable release) on Windows 10.

**Comment by marticliment** [comment]
Hello,

I am afraid that this is an issue that cannot be fixed due to the way in which Windows works. Each process (and their children) have their immutable env variables at launch, and they are not updated until the program is restarted. I am afraid that this is not a but with WingetUI, but rather an issue with how Windows handles env variables

**Comment by Wallby** [comment]
@marticliment

> I am afraid that this is an issue that cannot be fixed due to the way in which Windows works. Each process (and their children) have their immutable env variables at launch, and they are not updated until the program is restarted. I am afraid that this is not a but with WingetUI, but rather an issue with how Windows handles env variables

I read here that explorer.exe will send (i.e. HWND_BROADCAST) a WM_SETTINGCHANGE to all windows if an environment variable was modified.. https://serverfault.com/a/8856

> After the changes are saved, Explorer broadcasts a WM_SETTINGCHANGE message to all windows to inform them of the change. Any programs spawned via Explorer after this should get the updated environment, although already-running programs will not, unless they handle the setting change message.

**Comment by marticliment** [comment]
I will explore this
