### ISSUE TITLE
[ENHANCEMENT] Manual check for WingetUI update (not package updates)

### ISSUE THREAD

**Issue by redactedscribe** [marticliment/UniGetUI#1942]
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and have not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This improvement refers to an existing feature. If you want to suggest a new feature, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=new-feature&projects=&template=feature-request.yml&title=%5BFEATURE+REQUEST%5D+%28Enter+your+description+here%29)
- [X] This improvement is not a bug. If you want to report a bug, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=bug&projects=&template=bug-issue.yml&title=%5BBUG%5D+%28Enter+your+description+here%29)

### Describe the improvement

There doesn't appear to be a way to manually check for an available update for the program itself. We only have the setting "Update WingetUI automatically". The sidebar's "..." more menu could contain an option "Check for WingetUI update" or similar. A "Check now" button / link could also be next to the "Update WingetUI automatically" option in the settings.

![WingetUI_2024-03-14_11-36-30](https://github.com/marticliment/WingetUI/assets/25013746/51ec2a56-6323-4444-8b53-c7abeb82e009)

### Describe how this improvement could help users.

If users do not want to enable automatic updating of WingetUI, they can still manually check for an update, and ideally then choose whether to install it or not.

**Comment by marticliment** [comment]
You need to enable "Update UniGetUI automatically" for the button to be enabled. There is an open support ticket for this to be fixed.
