### ISSUE TITLE
[BUG] update selected packages twice

### ISSUE THREAD

**Issue by Uj947nXmRqV2nRaWshKtHzTvckUUpD** [marticliment/UniGetUI#2002]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

able to press 'update selected packages' multiple times

### Steps to reproduce the issue

have apps updateable
click 'update selected packages'
quickly click again 'update selected packages'
the queue gets duplicates with the apps to update

### WingetUI Log

```text
N/a
```

### Package Managers Logs

```text
N/a
```

**Comment by marticliment** [comment]
> quickly click again 'update selected packages'

What do you mean? I an accidental way?
If you click a button twice, the action is is expected to run again, right?

**Comment by marticliment** [comment]
Sometimes it is a useful practice to add a package operation twice, for example to mitigate temporary internet issues or open files or similar. 

I personally do so sometimes, and I am aware of other users that also do such practices. I will try implement some double-click preventor, but I will not disable duplicate items in queue

**Comment by SynapseScribe** [comment]
hi. this bug is still present. when i click <update selection> twice in a row, the updates are duplicated in the queue

**Comment by marticliment** [comment]
Yes, the fix was merged but a new version with the new code has not been released yet
