### ISSUE TITLE
[FEATURE REQUEST] Make a 'Check for Updates' button

### ISSUE THREAD

**Issue by skanda890** [marticliment/UniGetUI#2047]
### Please confirm these before moving forward

- [X] I have searched for my feature proposal and have not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This proposal is a completely new feature. If you want to suggest an improvement or an enhancement, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=enhancement&projects=&template=enhancement-improvement.yml&title=%5BENHANCEMENT%5D+%28Enter+your+description+here%29)

### Describe the new feature

Make a 'Check for Updates' button in 
![image](https://github.com/marticliment/WingetUI/assets/99239826/5ba4c03d-e5c7-4561-a0fc-87390be4828b)

### Describe how this new feature could help users.

This feature could be used to check for updates.

**Comment by marticliment** [comment]
Check for updates, in which sense? Check for updates means for WingetUI only or for all packages?

**Comment by skanda890** [comment]
> Check for updates, in which sense? Check for updates means for WingetUI only or for all packages?

For WingetUI.
