### ISSUE TITLE
How to modify the package manager configuration information in the WingetUI configuration file?

### ISSUE THREAD

**Issue by Leige458** [marticliment/UniGetUI#2111]
Originally, I had installed chocolatey, scoop and powershell7 on my laptop before, but after installing WingetUI, the package manager option in the settings did not find the correct configuration.

So I would like to request the developers to add an option to manually select the package manager configuration information in the settings.

**Comment by marticliment** [comment]
Hi,

You can enable using system chocolatey on WinGetUI.
System Scoop is already used by default.
PWSH7 is a request that will be implemented soon

**Comment by marticliment** [comment]
Does this solve the issue?
