### ISSUE TITLE
[BUG] Notifications take focus from active window

### ISSUE THREAD

**Issue by Courtland9777** [marticliment/UniGetUI#2332]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

When I am gaming, my game exits to the desktop when a wingetui notification occurs. It doesn't exit the game the notification takes the focus similar to hitting alt + tab. I have confirmed this behavior is from wingetui using the window focus logger. My OS is Windows 11. Disabling notifications prevents this from happening. 

### WingetUI Log

```text
Unavailable
```

### Package Managers Logs

```text
Unavailable
```

**Comment by marticliment** [comment]
Which WingetUI version?

**Comment by Courtland9777** [comment]
WingetUI Version 3.0.2

**Comment by marticliment** [comment]
And notifications from other apps don't affect the foreground window?

**Comment by Courtland9777** [comment]
I have not experienced any issues with other notifications.

**Comment by marticliment** [comment]
Do you have focus assistant enabled when gaming?

**Comment by Courtland9777** [comment]
Yes, it's set to automatically enable when in full screen mode.

**Comment by marticliment** [comment]
But does it really get enabled? There are some games that, when on fullscreen, are not detected as fullscreen apps since they are directly rendered on-screen by DirectX/OpenGL/Vulkan APIs, skipping the desktop/window manager. Therefore, they do not trigger focus assistant

**Comment by Courtland9777** [comment]
I'm playing StarCraft 2.

**Comment by marticliment** [comment]
I will see what I can find

**Comment by Courtland9777** [comment]
Thank you.
