### ISSUE TITLE
[BUG] 3.1.0 Beta 1 - PowerShell - Write-Output : The term '﻿Write-Output' is not recognized as the name of a cmdlet, function, script file

### ISSUE THREAD

**Issue by RonnyTNL** [marticliment/UniGetUI#2379]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.1.0 b1

### Windows version, edition and architecture

Win10 x64

### Describe your issue

Package manager log shows error on PowerShell command.

### Steps to reproduce the issue

Run 3.1.0 beta1 as standard/limited user

### UniGetUI Log

```text
N/A
```

### Package Managers Logs

```text
Logged subprocess-based task on manager Winget. Task type is ListPackages
Subprocess executable: "C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe"
Command-line arguments: "-ExecutionPolicy Bypass -NoLogo -NoProfile"
Process start time: 01/07/2024 16:49:00
Process end time:   01/07/2024 16:49:14

-- Process STDIN
 ...

-- Process STDOUT
 ...

-- Process STDERR
  Write-Output : The term '﻿Write-Output' is not recognized as the name of a cmdlet, function, script file, or 
  operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try 
  again.
  At line:1 char:1
  + ﻿Write-Output (Get-Module -Name Microsoft.WinGet.Client).Version
  + ~~~~~~~~~~~~~~~
      + CategoryInfo          : ObjectNotFound: (﻿Write-Output:String) [], CommandNotFoundException
      + FullyQualifiedErrorId : CommandNotFoundException
   

Return code: SUCCESS (0)
```

### Relevant information

This error occurs 2 times in the log on the PowerShell commands.
Task type is ListPackages
Task type is ListUpdates

**Comment by marticliment** [comment]
This is due to some weird characters appearing on the parsed console. Don't worry about them, in fact, the `Write-Output [...]` line is present there so that it _captures_ the ZWNBSP character and does not hinder the actual real commands, executed afterwards.

What I mean:
![image](https://github.com/marticliment/WingetUI/assets/53119851/5357f55e-677b-4c52-b74d-b92feb228163)


I don't know yet what causes this character to appear, since in my machine this does not happen, but don't worry about it.

**Comment by RonnyTNL** [comment]
Ok thanks, I'll give it a spin in a VM tomorrow see if I can reproduce this behavior.

**Comment by RonnyTNL** [comment]
Reproduces on a VM also, perhaps regional settings or something?

**Comment by marticliment** [comment]
What are your regional settings?

**Comment by RonnyTNL** [comment]
![image](https://github.com/marticliment/WingetUI/assets/19427356/1280fdea-7f69-4630-96f0-7c743dd673f6)
