### ISSUE TITLE
[BUG] Cannot install beta release

### ISSUE THREAD

**Issue by DarthSonic** [marticliment/UniGetUI#2396]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.1.0 beta 2

### Windows version, edition and architecture

Windows 11 Pro, 23H1, x64

### Describe your issue

When trying to install latest beta, this error happens:
![image](https://github.com/marticliment/WingetUI/assets/3968605/e9dabe60-e6fe-4427-90a5-01858fc4366d)

File cannot be executed in temporary folder. Access denied.

### Steps to reproduce the issue

Open install file.

### UniGetUI Log

```text
-
```

### Package Managers Logs

```text
-
```

### Screenshots and videos

![image](https://github.com/marticliment/WingetUI/assets/3968605/e9dabe60-e6fe-4427-90a5-01858fc4366d)

**Comment by marticliment** [comment]
Please try disabling the AV

**Comment by DarthSonic** [comment]
Worked. Thanks!

**Comment by marticliment** [comment]
Please try whitelisting UniGetUI

**Comment by DarthSonic** [comment]
With the stable release the issue is gone.
