### ISSUE TITLE
[ENHANCEMENT] Desktop shortcut should include new logo

### ISSUE THREAD

**Issue by vikingnope** [marticliment/UniGetUI#2397]
### Please confirm these before moving forward.

- [X] I have searched for my feature proposal and have not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This improvement refers to an existing feature. If you want to suggest a new feature, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=new-feature&projects=&template=feature-request.yml&title=%5BFEATURE+REQUEST%5D+%28Enter+your+description+here%29).
- [X] This improvement is not a bug. If you want to report a bug, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=bug&projects=&template=bug-issue.yml&title=%5BBUG%5D+%28Enter+your+description+here%29).

### Describe the improvement

Currently Desktop hortcut with 3.1.0 is still using the old logo, should be changed to the new one.

![image](https://github.com/marticliment/UniGetUI/assets/81376423/66799a27-74cc-4e60-9c4e-4703b78c2fcc)

### Describe how this improvement could help users

Shows further the modern theme

**Comment by marticliment** [comment]
It does, but due to icon caching by file explorer it might take some time to update
