### ISSUE TITLE
[BUG] `marticliment.com/unigetui` images broken due to rename

### ISSUE THREAD

**Issue by o-l-a-v** [marticliment/UniGetUI#2398]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

Not relevant

### Windows version, edition and architecture

Not relevant

### Describe your issue

Congrats on the rename! 🥳

The images used by <https://www.marticliment.com/unigetui/> has been renamed in this GitHub repo ( <https://github.com/marticliment/UniGetUI/tree/main/media> ) and thus are broken.

<img width="1277" alt="image" src="https://github.com/marticliment/UniGetUI/assets/6450056/f890ddca-4616-45ec-a73c-cf0277834489">

### UniGetUI Log

```text
Not relevant.
```

### Package Managers Logs

```text
Not relevant.
```

**Comment by marticliment** [comment]
I am working on this right now, but thanks for the report!
