### ISSUE TITLE
[BUG] untranslated text strings in 3.1.0

### ISSUE THREAD

**Issue by Stephan-P** [marticliment/UniGetUI#2405]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.1.0

### Windows version, edition and architecture

Win 11

### Describe your issue

The text "Loading packages" that is displayed in the tab Software updates is not translated (in Dutch)
Probably a fault pointer

### Steps to reproduce the issue

Open the tab Software Updates
Click Refresh

### UniGetUI Log

```text
See attachment
```

### Package Managers Logs

```text
N.A.
```

### Screenshots and videos

[UniGetUI-logboek.txt](https://github.com/user-attachments/files/16083848/UniGetUI-logboek.txt)

**Comment by Stephan-P** [comment]
More untranslated in 3.10
![image](https://github.com/marticliment/UniGetUI/assets/10008599/1df05ef3-2fe2-4fea-9f07-9de5bf7224d2)

![image](https://github.com/marticliment/UniGetUI/assets/10008599/90c6c024-3e1c-40b9-b536-92cbca470fa8)

![image](https://github.com/marticliment/UniGetUI/assets/10008599/cc678058-e9b9-4f06-a3a3-1a4a9937a737)

**Comment by Stephan-P** [comment]
Ah, those are new ones in Tolgee. 
I took care of these. Let's keep an eye for the next update.

**Comment by marticliment** [comment]
Yes, they will take 24/48h to get updated
