### ISSUE TITLE
Can't install - Paket-ID:  SomePythonThings.WingetUIStore.Pre-release

### ISSUE THREAD

**Issue by Paul051962** [marticliment/UniGetUI#2421]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.1.0

### Windows version, edition, and architecture

Windows 11 Pro 22631.3810

### Describe your issue

Ich hatte gestern das Update auf UniGetUI installiert und im Anschluss wurde mir das u.a. Paket zur Installation angezeigt.
Ich habe mehrfach, auch als Admin, versucht das Paket "Paket-ID:  SomePythonThings.WingetUIStore.Pre-release" zu installieren, aber leider ohne Erfolg. Die beigefügten Screenshots zeigen das Problem im Detail. 
Wie kann ich das Problem lösen?

### Steps to reproduce the issue

Das Installationsproblem wiederholt sich bei jedem Versuch, das Paket zu installieren. Auch ein Neustart des Computers war ohne Erfolg.

### UniGetUI Log

```text
Starting package update operation for package id=SomePythonThings.WingetUIStore.Pre-release with Manager name=Winget
Given installation options are <InstallationOptions: SkipHashCheck=False;InteractiveInstallation=False;RunAsAdministrator=True;Version=;Architecture=;InstallationScope=;InstallationScope=;CustomParameters=;RemoveDataOnUninstall=False>
Process Executable     : C:\Program Files\WingetUI\Assets\Utilities\gsudo.exe
Process Call Arguments : "C:\Users\pkhro\AppData\Local\Microsoft\WindowsApps\winget.exe"  update --id SomePythonThings.WingetUIStore.Pre-release --exact --source winget --accept-source-agreements --version "3.1.0-beta1" --silent --disable-interactivity --accept-package-agreements --force --include-unknown
Working Directory      : C:\Users\pkhro
    |    - 
    | Es wurde kein anwendbarer Installer gefunden. Weitere Informationen finden Sie in den Protokollen.
Process Exit Code      : -1978335216
Process End Time       : 04.07.2024 07:02:35
```

### Package Managers Logs

```text
winget.exe update --id SomePythonThings.WingetUIStore.Pre-release --exact --source winget --accept-source-agreements --version "3.1.0-beta1" --silent --disable-interactivity --accept-package-agreements --force --include-unknown
```

### Screenshots and videos

![UniGetUi-1](https://github.com/marticliment/UniGetUI/assets/88423032/0cfd8003-24d2-4c09-be21-4a00450ef081)
![UniGetUi-2](https://github.com/marticliment/UniGetUI/assets/88423032/c2e5ea5c-e6ae-4da8-96be-da654aff738b)
![UniGetUi-3](https://github.com/marticliment/UniGetUI/assets/88423032/9377347f-4b39-4882-81e5-948853c5c258)

**Comment by marticliment** [comment]
duplicate of #2399

**Comment by marticliment** [comment]
Do not install this release
