### ISSUE TITLE
[BUG] Cannot prevent auto update to v3.1.0 and 3.1.0 does not work

### ISSUE THREAD

**Issue by wiz2003** [marticliment/UniGetUI#2436]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.0.2

### Windows version, edition, and architecture

 Microsoft Windows 11 Pro X64 10.0.22631 Build 22631

### Describe your issue

Unigetui 3.1.0 does not work because of a powershell error - Wingetui 3.0.2 works fine.
So, uninstall wingetui
install wingetui
disable network adaptors
run wingetui
disable auto update of wingetui in settings
enable network
wingetui always downloads unigetui v.1.0 upon start
wingetui always runs the installer to update to v 3.1.0 upon exit.
even if the prompt to update is cancelled, wingetui will not now load.
If the update is run, the installer loops on 
ensuring wingetui is installed properly
When the install is abandoned and the program started....
The program is useless as you always get the message
Missing dependency
UniGetui requires Winget Powershell moduleto operate, but it was not found.

It is not possible to resolve this issue..

I am forced to uninstall and cease using wingetui / unigetui

I have log files and screen shots
[wingetui 3.1.0 log 4.txt](https://github.com/user-attachments/files/16109309/wingetui.3.1.0.log.4.txt)
[wingetui 3.1.0 log 3.txt](https://github.com/user-attachments/files/16109310/wingetui.3.1.0.log.3.txt)
![error whenever unigetui 3 1 0 is started](https://github.com/marticliment/UniGetUI/assets/18750228/ce587963-4cd4-405a-84c4-27f63b39a4e1)
![wingetui updates when updates disabled](https://github.com/marticliment/UniGetUI/assets/18750228/06a1d017-b416-4a10-b0fd-685985f20adb)
![update to unigetui 3 1 0 loop](https://github.com/marticliment/UniGetUI/assets/18750228/5b0154f9-f3ed-46d4-bf94-b5e7e1c7e61b)
[wingetui 3.0.2 log 2.txt](https://github.com/user-attachments/files/16109313/wingetui.3.0.2.log.2.txt)
[wingetui 3.0.2 log 1.txt](https://github.com/user-attachments/files/16109314/wingetui.3.0.2.log.1.txt)
 of each stage

### Steps to reproduce the issue

See issue description

### UniGetUI Log

```text
as attached
```

### Package Managers Logs

```text
Not relevant
```

### Screenshots and videos

as uploaded

**Comment by marticliment** [comment]
After disabling updates on Version 3.0.2, kill WingetUI from the task manager. It should not update anymore

**Comment by wiz2003** [comment]
Thank you - tried that......
Does not make any difference

**Comment by marticliment** [comment]
Please follow this guide to downgrade:

https://github.com/marticliment/UniGetUI/issues/2438

**Comment by marticliment** [comment]
Hello, please follow [this guide](https://github.com/marticliment/UniGetUI/issues/2438) in order to downgrade WingetUI

**Comment by almeath** [comment]
Same thing happening for me on Windows 11 23H2 (KB5039212). Everything was working fine as WinGetUI but after the upgrade to UniGetUI I am stuck in a constant loop, as described above. It tells me I have a missing dependency - so I click the option to install it, then restart the app, only for the process to begin again. I definitely have the module installed, and even did so manually under PowerShell 7 just to make sure it was not an error with my system or PowerShell install. The app is now useless for me because it will not detect any package upgrades and I cannot get past this "missing dependency" issue.

![Screenshot 2024-07-06 051344](https://github.com/marticliment/UniGetUI/assets/5726214/7add930d-ba68-45f2-98b6-545e4e456c63)

![Screenshot 2024-07-06 051318](https://github.com/marticliment/UniGetUI/assets/5726214/2fe62f35-b470-402e-9b98-42152807838c)

**Comment by almeath** [comment]
It if  helps, when I click the option to "Install WinGet PowerShell Module" it defaults to trying to install it under Windows Powershell (5) which then fails with this error:

```
Install-Module : The term 'Install-Module' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of
the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:4
+ & {Install-Module -Name Microsoft.WinGet.Client -Force -Confirm:$fals ...
+    ~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Install-Module:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

So that is why I manually installed the module under PowerShell 7 in administrator mode, only to have UniGetUI continually display the messages in my post above.

**Comment by marticliment** [comment]
Try to install the module on PowerShell 5.1

**Comment by marticliment** [comment]
Hello,

To all users facing issues with version 3.1.0, please try the new 3.1.1 beta, which aims to fix this issues.

UniGetUI 3.1.1-beta0 release: https://github.com/marticliment/UniGetUI/releases/tag/3.1.1-beta0
Direct installer URL: https://github.com/marticliment/UniGetUI/releases/download/3.1.1-beta0/UniGetUI.Installer.exe

Excuse me for the inconveniences.

**Comment by almeath** [comment]
> Try to install the module on PowerShell 5.1

That is what I did. I have 5.1 installed under Windows 11, and I tried installing manually under that and also separately under PowerShell 7. In either case, UniGetUI is not recognizing I have installed the module, and keeps prompting for it.

**Comment by almeath** [comment]
> Hello,
> 
> To all users facing issues with version 3.1.0, please try the new 3.1.1 beta, which aims to fix this issues.
> 
> UniGetUI 3.1.1-beta0 release: https://github.com/marticliment/UniGetUI/releases/tag/3.1.1-beta0 Direct installer URL: https://github.com/marticliment/UniGetUI/releases/download/3.1.1-beta0/UniGetUI.Installer.exe
> 
> Excuse me for the inconveniences.

Unfortunately, the Beta release suffers from the same issue.

They only thing that works for me at this stage, is downgrading back to WinGetUI 3.0.2  - everything went back to normal after that and my package updates are showing up again. I would think that this proves the helper module is installed properly.

**Comment by marticliment** [comment]
On the beta, please go to Settings -> WinGet -> enable Use legacy bundled winget

**Comment by wiz2003** [comment]
Will try that shortly...

**Comment by almeath** [comment]
> On the beta, please go to Settings -> WinGet -> enable Use legacy bundled winget

Thanks - seems to have settled down now. But I still had to click the option not to be reminded each time the app starts up, as it keeps saying I do not have the PowerShell module installed. However, it does now bypass this and uses the legacy in-built version, so the updates still work.

**Comment by marticliment** [comment]
I will fix this on the next version

**Comment by wiz2003** [comment]
Thank you
