### ISSUE TITLE
removed unselect all button [If duplpicate I want it duplicated to indicate my severity]

### ISSUE THREAD

**Issue by CowboyRobotInDisguise** [marticliment/UniGetUI#2437]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

302

### Windows version, edition, and architecture

win 10 latest

### Describe your issue

removed the unselect all button

### Steps to reproduce the issue

use you eye balls

### UniGetUI Log

```text
not necessary
```

### Package Managers Logs

```text
again not necessary
```

### Relevant information

put it back

### Screenshots and videos

again not necessary

**Comment by CowboyRobotInDisguise** [comment]
how about this email me if you put it back. between this and the advert cookies i removed it in about 10 seconds

**Comment by marticliment** [comment]
![image](https://github.com/marticliment/UniGetUI/assets/53119851/16890579-db69-4c93-b743-72a8290859bd)
In fact, use your eyeballs

**Comment by CowboyRobotInDisguise** [comment]
and that is why i went ahead and deleted it. that was the reply i expected, thanks

________________________________________
