### ISSUE TITLE
[ENHANCEMENT] Show download speed for downloading package

### ISSUE THREAD

**Issue by redactedscribe** [marticliment/UniGetUI#2442]
### Please confirm these before moving forward.

- [X] I have searched for my feature proposal and have not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This improvement refers to an existing feature. If you want to suggest a new feature, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=new-feature&projects=&template=feature-request.yml&title=%5BFEATURE+REQUEST%5D+%28Enter+your+description+here%29).
- [X] This improvement is not a bug. If you want to report a bug, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=bug&projects=&template=bug-issue.yml&title=%5BBUG%5D+%28Enter+your+description+here%29).

### Describe the improvement

I'd like to be able to see the speed at which a package is downloading here:

![WingetUI_2024-07-06_02-58-48](https://github.com/marticliment/UniGetUI/assets/25013746/51a7f6ff-d6a2-4dfd-aa91-d642cc4a4384)

### Describe how this improvement could help users

Seeing X / X MB is fine, but it's quite normal I think to be interested in what the actual download speed is. Sometimes it seems like packages are stuck downloading, and seeing 50 Kb/s instead 0 Kb/s might influence your decision to cancel the update or not.

**Comment by marticliment** [comment]
This info is not displayed by the Package Managers, and therefore if the download speed is not shown, it cannot be shown on UniGetUI

**Comment by marticliment** [comment]
Will investigate
