### ISSUE TITLE
[BUG] Page not found 404 error for Release notes

### ISSUE THREAD

**Issue by DrStrange** [marticliment/UniGetUI#2447]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.1.1 beta 0

### Windows version, edition, and architecture

Windows 10 Enterprise x64  10.0.19045.4598

### Describe your issue

Choosing release notes on` ... More` opens a page not found 404 error on GitHub. (The page asks you to login even though I'm already logged in to GitHub so I logged in on the 404 error page and restarted UnigetUI but still get a 404 error).

marti thanks for all the work you've done on UnigetUi, especially since Sumo closed. I haven't had any issues since 3.1.0 (apart from the STDERR Write-Output cosmetic fault which anyway is now fixed). Great to have somthing as good as Sumo for free.

### Steps to reproduce the issue

Click on `... More` and choose Release notes from popup. 404 error page opens. 

### UniGetUI Log

```text
Can provide if needed but don't see any error message in it
```

### Package Managers Logs

```text
Can provide if needed but don't see any error message in it
```

### Relevant information

No error in Operation history

### Screenshots and videos

![release notes](https://github.com/marticliment/UniGetUI/assets/443688/0ba15b89-1a7d-4346-8f4a-974c5a5efd41)

**Comment by marticliment** [comment]
I am aware. I accidentally changed the version number with the version string. This will be fixed on future releases

**Comment by marticliment** [comment]
Fixed on latest beta
