### ISSUE TITLE
Please add more UniGetUI update options in addition to "Update UniGetUl automatically"

### ISSUE THREAD

**Issue by ZPNRG** [marticliment/UniGetUI#2448]
### Please confirm these before moving forward.

- [X] I have searched for my feature proposal and have not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This proposal is a completely new feature. If you want to suggest an improvement or an enhancement, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=enhancement&projects=&template=enhancement-improvement.yml&title=%5BENHANCEMENT%5D+%28Enter+your+description+here%29).

### Describe the new feature

Hi.  I was not sure if this would be considered more of an "improvement or an enhancement" to an existing feature or a new feature.  I think it is somewhat a new feature and somewhat an improvement/enhancement to existing functionality.

I would like to have more options for checking for updates, including at least the beta-level releases, and if there is an update, then being able to tell UniGetUI to go ahead and perform the udpate.

In addition to the checkbox for "_**Update UniGetUl automatically**_", I would like the following added to UniGetUI:

1) "_**Check now for UniGetUI updates**_" button -- 
Admittedly, if UniGetUI is very quick and reliable about checking for updates when it is launched or there was some setting to tell it to check every X minutes/hours/days, then this button is probably not necessary.  However, I prefer to check manually.  I do not leave UniGetUI running all of the time.  I launch it regularly, check for updates for the packages, install them, and then usually close UniGetUI.

2) This option/functionality ties in with 1) (above) and 3) (below).  I have included a screenshot showing Paint.net's Updates options, which includes a "_**Also check for pre-release (beta) versions of paint.net**_".  

![Paint net Updates options](https://github.com/marticliment/UniGetUI/assets/28507509/3212249f-fb96-45be-8851-9fb4a80d0bca)

I would like a sub-option similar to this (for example, "_**Also check for beta-level releases of UniGetUI**_") to tell UniGetUI to check for beta-level releases.  Sure, you could have two sub-options, one for alpha-level releases and one for beta-level releases, but I personally would not want to have UniGetUI offer to "Install now" (or "Update now") [ see 3) below ] on the fly any release that wasn't at least beta-level.  For safety reasons, I personally think it is probably best NOT to offer alpha releases to a user.  Alpha releases are probably best to be manually installed. **#** (see below)

3) I would like to see the option to manually tell UniGetUI to update to a release from within the program and not rely on the "_**Update UniGetUI automatically**_" option.  This option would not need to be tied to the aforementioned "_**Check now for UniGetUI updates**_" button.  It could be that if the "_**Update UniGetUI automatically**_" option is unchecked/disabled, then UniGetUI notifies the user that there is an available update.  Whether UniGetUI checks on its own or the user manually uses the "_**Check now for UniGetUI updates**_" button, a notification about an available update would notify the user of releases based on whether the option "_**Also check for beta-level releases of UniGetUI**_" is enabled/checked or not.  If it is NOT enabled/checked, then only final/stable releases are considered and brought to the user's attention.  If that option is enabled/checked, then beta releases are also checked for and offered to the user. Depending on if a release was available (final/stable or beta-level - depending on the settings enabled), UniGetUI would ideally then have a "_**Install now**_" or "_**Update now**_" button.  If the user runs that, then UniGetUI would perform the update.  I do think that this "Install/Update now" button should somehow tie into or lead to 4) below.  

**#** As a side note, going back to 2) above, you could add a "_**Also check for alpha-level releases of UniGetUI**_" option and make it clear to the user that they will be notified if one is available, but for their safety, alpha releases must be downloaded and installed manually.  Whether the benefits of this outweigh the complexity or trouble, I do not know.  I guess the question is do you want more alpha release testers or about the same level that you already have?

4) Probably somewhere in all of this, it would be a good idea to...
1] offer the user a button to "_**Backup all UniGetUI settings and installed packages**_",  OR 
2] offer the user two shortcut buttons, one for "_**Export settings to a local file**_" and one for "_**Perform a backup of the installed packages**_",  OR 
3] at least encourage the user to go and do both of the tasks in 2] above (Export settings and Perform a backup)

### Describe how this new feature could help users

This would be helpful for any user that wants more control over checking for UniGetUI updates, including beta-level (and/or possibly alpha-level updates), and then being given the option to install an available update.  This is especially useful for those that do not want to rely on the "_**Update UniGetUl automatically**_" option.

**Comment by ZPNRG** [comment]
@marticliment  Sorry, I've been cleaning up and improving my issue/suggestion after I posted it.  I thought I had it all written up nicely and then I found what I felt were improvements or more tweaking to the suggestion(s).  (Face palm)

**Comment by marticliment** [comment]
> 4\. Probably somewhere in all of this, it would be a good idea to...
>     1] offer the user a button to "_**Backup all UniGetUI settings and installed packages**_",  OR
>     2] offer the user two shortcut buttons, one for "_**Export settings to a local file**_" and one for "_**Perform a backup of the installed packages**_",  OR

You can do both of those things:
 - Backup pages has its own section on the settings 
 - Settings can be exported from the "General preferences section"

**Comment by ZPNRG** [comment]
@marticliment  I understand that and use those settings.  

My point is, it would possibly be a good idea to ...

1] offer the user a single button to "Backup all UniGetUI settings and installed packages", OR
2] offer the user two shortcut buttons, one for "Export settings to a local file" and one for "Perform a backup of the installed packages", OR
3] at least encourage the user to go and do both of the tasks in 2] above (Export settings and Perform a backup)

right there with a "Install now" or "Update now" button (so the user doesn't have to leave and go do those tasks) (in the case of 1] or 2] or to at least reference those options (3] above) in case the user isn't aware of them.  If nothing else, perhaps encourage the user to consider backing up their UniGetUI settings and/or installed packages if they have not done so.  This would be worth considering whether the user is aware of them (and uses them) like I do or not.

**Comment by marticliment** [comment]
Oh, I see

**Comment by ZPNRG** [comment]
Sorry for not maybe articulating that as clearly at the beginning as I meant to.

**Comment by ZPNRG** [comment]
@marticliment, thank you.  I look forward to testing this in a UniGetUI build.
