### ISSUE TITLE
[BUG] "No results were found matching the input criteria"

### ISSUE THREAD

**Issue by redactedscribe** [marticliment/UniGetUI#2453]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.1.1-beta1

### Windows version, edition, and architecture

Windows 11 Pro

### Describe your issue

After launching UniGetUI, the Software Packages tabs shows "No results were found matching the input criteria" after UniGetUI checks for updates instead of showing the packages available to update.

### Steps to reproduce the issue

Launch UniGetUI.

### UniGetUI Log

```text
-
```

### Package Managers Logs

```text
-
```

### Relevant information

You must enter something into the search field then clear it for the packages to be revealed.

**Comment by marticliment** [comment]
Fixed by 0a86316fddc7a90102e77e6dda661b703f2308bc
