### ISSUE TITLE
Windows user folder with 'à' accent

### ISSUE THREAD

**Issue by albert-ubintia** [marticliment/UniGetUI#2455]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.10

### Windows version, edition, and architecture

Windows 11 PRO 23H2 - 22631.3810

### Describe your issue

Hello,

The program cannot use the winget folder, I have seen that my user's folder has an accented letter 'à' and I think that makes UniGetUi unable to use it.

Winget from the command line works correctly.

### UniGetUI Log

```text
[08/07/2024 8:44:41] 
                        __  __      _ ______     __  __  ______
                       / / / /___  (_) ____/__  / /_/ / / /  _/
                      / / / / __ \/ / / __/ _ \/ __/ / / // /  
                     / /_/ / / / / / /_/ /  __/ /_/ /_/ // /   
                     \____/_/ /_/_/\____/\___/\__/\____/___/   
                         Welcome to UniGetUI Version 3.1.0
[08/07/2024 8:44:41]
[08/07/2024 8:44:41] Version Code:  3,1
[08/07/2024 8:44:41] Using bundled GSudo at C:\Program Files\UniGetUI\Assets\Utilities\gsudo.exe
[08/07/2024 8:44:41] Loaded language locale: es
[08/07/2024 8:44:42] Randomly-generated background API auth token for the current session: hw2zt6dcrueitds12n8lwlkkv5cuygxn3xkw090doh3gg6j60psek7crud3rdmcf
[08/07/2024 8:44:42] Api running on http://localhost:7058
[08/07/2024 8:44:43] Lang files were updated successfully from GitHub
[08/07/2024 8:44:43] UniGetUI is up to date
[08/07/2024 8:44:43] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                     █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                     █ Name: Winget
                     █ Enabled: True
                     █ Found: False
                     █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                     █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                     ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[08/07/2024 8:44:43] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                     █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                     █ Name: Pip
                     █ Enabled: False
                     █ THE MANAGER IS DISABLED
                     ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[08/07/2024 8:44:44] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                     █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                     █ Name: PowerShell
                     █ Enabled: False
                     █ THE MANAGER IS DISABLED
                     ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[08/07/2024 8:44:45] Downloaded new icons and screenshots successfully!
[08/07/2024 8:44:45] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                     █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                     █ Name: .NET Tool
                     █ Enabled: False
                     █ THE MANAGER IS DISABLED
                     ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[08/07/2024 8:44:45] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                     █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                     █ Name: Chocolatey
                     █ Enabled: False
                     █ THE MANAGER IS DISABLED
                     ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[08/07/2024 8:44:47] Command scoop was not found on the system
[08/07/2024 8:44:47] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                     █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                     █ Name: Scoop
                     █ Enabled: False
                     █ THE MANAGER IS DISABLED
                     ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[08/07/2024 8:44:48] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                     █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                     █ Name: Npm
                     █ Enabled: False
                     █ THE MANAGER IS DISABLED
                     ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[08/07/2024 8:44:49] LoadComponentsAsync finished executing. All managers loaded. Proceeding to interface.
```

### Package Managers Logs

```text
Manager Winget with version:


——————————————————————————————————————————
```

### Screenshots and videos

![image](https://github.com/marticliment/UniGetUI/assets/115785282/774b9bae-6028-47ca-93f6-a3f2314edce3)

**Comment by Mertsch** [comment]
@albert-ubintia Have you tried 3.1.1 beta? It includes a fix that sounds very much like it's for you

> Issues with package encoding
>   WinGet will be found on systems where the user does not have a ascii-only username

**Comment by marticliment** [comment]
Yes, the latest beta has this issue fixed

**Comment by albert-ubintia** [comment]
Hello,

I can confirm that the beta has solved my problem with the à character, you can see it in the following screenshot

![image](https://github.com/marticliment/UniGetUI/assets/115785282/fc1fc4d5-0121-49ff-8049-e02ecd3f31ef)

Thank you all for such a quick response.

**Comment by iggsn** [comment]
Hey @albert-ubintia,

have you done anything special? I completely uninstalled WinGet 3.0.2 and also deleted the folders in Local App Data.
I reinstalled the latest beta (as seen in the screenshot).

However it still shows the acronym "ü" as a squared box, if I copy the path.

So for me it doesn't work yet :-(

**Comment by albert-ubintia** [comment]
No, I haven't done anything special, just uninstall the regular version and install the beta.
Before uninstalling the beta, I did do a reset in the general preferences and the Winget section.

**Comment by joaroyen** [comment]
This is still an issue for me running 3.1.1-beta1 where UniGetUI displays "Winget not found" error. I have an `Ø` in my username which is replaced with an `O` in the path to winget.exe as displayed in the settings dialog. 

I've created a junction using uppercase O that points to my real user folder as a workaround.

**Comment by tdoerschel** [comment]
I can confirm that Uniget 3.1.1-beta3 "fixes" the issue by pointing to
C:\Program Files\WingetUI\winget-cli_x64\winget.exe 
instead of the users \AppData\Local\Microsoft\WindowsApps\winget.exe

**Comment by joaroyen** [comment]
I can confirm 3.1.1-beta3 fixed locating winget.exe but there is still an issue locating Scoop package manager and .NET Tools Outdated.
