### ISSUE TITLE
[ENHANCEMENT] (PowerShell Version Selection)

### ISSUE THREAD

**Issue by haoydeng** [marticliment/UniGetUI#2466]
### Please confirm these before moving forward.

- [X] I have searched for my feature proposal and have not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This improvement refers to an existing feature. If you want to suggest a new feature, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=new-feature&projects=&template=feature-request.yml&title=%5BFEATURE+REQUEST%5D+%28Enter+your+description+here%29).
- [X] This improvement is not a bug. If you want to report a bug, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=bug&projects=&template=bug-issue.yml&title=%5BBUG%5D+%28Enter+your+description+here%29).

### Describe the improvement

Let users choose between Windows PowerShell and PowerShell 7

### Describe how this improvement could help users

Let users choose between Windows PowerShell (5.1) and PowerShell 7

**Comment by marticliment** [comment]
duplicate if #1994
