### ISSUE TITLE
[BUG] Found packages count and filters do not update when a package is removed in the Package Bundles view

### ISSUE THREAD

**Issue by hboyd2003** [marticliment/UniGetUI#2470]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.1.1-beta1

### Windows version, edition, and architecture

Windows 11 Pro 22H2

### Describe your issue

When you remove a package from a package bundle the found packages count does not update not does the filters.

### Steps to reproduce the issue

1. Remove a package from a package bundle

### UniGetUI Log

```text
N/A
```

### Package Managers Logs

```text
N/A
```

### Screenshots and videos

![Bug](https://github.com/marticliment/UniGetUI/assets/8950185/7c09d8b5-64bd-4b8e-b9e0-00af293821fa)

**Comment by marticliment** [comment]
Will investigate
