### ISSUE TITLE
[BUG] [GUIDE] Some packages might get broken file type / extensions associations (MPV from Chocolatey in my case) after wingetui ⇾ unigetui migration

### ISSUE THREAD

**Issue by Msprg** [marticliment/UniGetUI#2477]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.1.0

### Windows version, edition, and architecture

Windows 11 Pro for Workstations 23H2 b22631.3880

### Describe your issue

In short, when using builtin chocolatey / scoop / wingetui tools, they are migrated to a different directory to reflect the name change rather harshly which broke a bunch of stuff for me.

Besides breaking some startup items, and some executables / shims disappearing from the %path%, one of the worst to troubleshoot was in my case broken mpv open source media player associations.

Symptoms:

When opening a file with broken association, "Choose a program to open this file with..." Windows dialog always opens instead.
The MPV option/s in the dialog are missing icon.
When broken mpv association is set as "open with by default app", in the file properties, there's "Unknown application" or "Unknown program" text instead of the application name (mpv).

Solution:

1. Uninstall all instances of mpv
2. Open windows registry editor
3. Navigate to `Computer\HKEY_CLASSES_ROOT\Applications\`
4. Look for `mpv.exe` subkey
5. Delete the whole `mpv.exe` subkey
6. Install mpv from Chocolatey again, make sure all installation scripts finish successfully.
7. In registry editor, press F5 to refresh, and check that `mpv.exe` subkey has been recreated by the installation scripts
8. File associations should now work.

### Steps to reproduce the issue

1. Install older version of wingetui and set it up with default settings,
2. Install mpv from chocolatey source,
3. Associate some media files to use mpv by default
4. Upgrade wingetui to unigetui
5. Associaton is broken after unigetui migrates data / %chocolateyinstall% directory.

### UniGetUI Log

```text
Irrelevant
```

### Package Managers Logs

```text
Irrelevant
```

**Comment by marticliment** [comment]
I will investigate this

**Comment by Msprg** [comment]
Thank you for your hard work! 

Have a nice day~!
