### ISSUE TITLE
right click OPEN LOCATION

### ISSUE THREAD

**Issue by grand-lotus-iroh** [marticliment/UniGetUI#2489]
### Please confirm these before moving forward.

- [X] I have searched for my feature proposal and have not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This improvement refers to an existing feature. If you want to suggest a new feature, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=new-feature&projects=&template=feature-request.yml&title=%5BFEATURE+REQUEST%5D+%28Enter+your+description+here%29).
- [X] This improvement is not a bug. If you want to report a bug, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=bug&projects=&template=bug-issue.yml&title=%5BBUG%5D+%28Enter+your+description+here%29).

### Describe the improvement

right click on installed package > open location

### Describe how this improvement could help users

common sense improvement

**Comment by haplopeart** [comment]
This is similar to a suggestion I was about to make.  Specifically in my case it is wanting to, but failing to update FFMPEG, which as far as I can tell is just a zip file extraction.  However I have NO idea where it is actually finding FFMpeg on on the disk.  So it would be cool if the UI/UX had an option to tell you were it actually found the thing it is trying to update in the file structure.

**Comment by eugenesvk** [comment]
Would be also nice to have this info in the "Package details" window
