### ISSUE TITLE
[BUG] Internal error; Cannot expand autopf64 contant on this version of Windows.

### ISSUE THREAD

**Issue by hawkeye73** [marticliment/UniGetUI#2501]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.1.0

### Windows version, edition, and architecture

Windows 10  22H2 Build 19045.4651 (32 bit)

### Describe your issue

Unable run setup on 32 bit version Windows 10. Machine is unable to run 64 bit version of Windows.

### Steps to reproduce the issue

I tried to install with different languages.

### UniGetUI Log

```text
I cant run UniGetUI.
```

### Package Managers Logs

```text
na
```

### Relevant information

32 bit Windows

### Screenshots and videos

![image](https://github.com/user-attachments/assets/288e44f0-d017-4dc7-93d7-8b424b28338d)

**Comment by marticliment** [comment]
UniGetUI is not compatible with 32bit versions of Windows
