### ISSUE TITLE
[FEATURE REQUEST] (Update option for PowerShell 7) 

### ISSUE THREAD

**Issue by tstager** [marticliment/UniGetUI#2504]
### Please confirm these before moving forward.

- [X] I have searched for my feature proposal and have not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This proposal is a completely new feature. If you want to suggest an improvement or an enhancement, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=enhancement&projects=&template=enhancement-improvement.yml&title=%5BENHANCEMENT%5D+%28Enter+your+description+here%29).

### Describe the new feature

Please allow an option to use Powershell 7 instead of 5.1 or add a separate updater for pwsh.exe.

### Describe how this new feature could help users

Most Powershell users are using Powershell 7 now.

**Comment by marticliment** [comment]
duplicate of #1994
