### ISSUE TITLE
[FEATURE REQUEST] Script setup

### ISSUE THREAD

**Issue by methanoid** [marticliment/UniGetUI#2507]
### Please confirm these before moving forward.

- [X] I have searched for my feature proposal and have not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This proposal is a completely new feature. If you want to suggest an improvement or an enhancement, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=enhancement&projects=&template=enhancement-improvement.yml&title=%5BENHANCEMENT%5D+%28Enter+your+description+here%29).

### Describe the new feature

Could we please be able to script setup so, for example, I could install UnigetUI from winget and then script "ignore updates for Microsoft Edge".

Main reason being I find removing Edge tends to break stuff like printing so I want to leave it but never waste time updating it

### Describe how this new feature could help users

Quicker automated setup

**Comment by mrixner** [comment]
Do you mean like automatically setting Microsoft Edge as an ignored update? If so, you can just set the `%LOCALAPPDATA%\UniGetUI\IgnoredPackageUpdates.json` to `{"winget\\Microsoft.Edge":"*"}` in your own batch file without having to ask UniGetUI to do it.

**Comment by marticliment** [comment]
Yes, you should be able to modify the settings.
However, please note that you will need to restart UniGetUI for the changes to take effect

**Comment by methanoid** [comment]
Thanks. I've since decided easier to remove Edge completely and also is was unreliable to install WinGet (on LTSC) by script so I just use Chocolatey now.. but this is useful should that ever change for me
