### ISSUE TITLE
[BUG] Cannot find file at '..\lib\ssh-copy-id\tools\ssh-copy-id.cmd'

### ISSUE THREAD

**Issue by heartacker** [marticliment/UniGetUI#2514]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.1.1 beta

### Windows version, edition, and architecture

win11

### Describe your issue

Cannot find file at '..\lib\ssh-copy-id\tools\ssh-copy-id.cmd' (C:\Users\Acker Liu\AppData\Local\UniGetUI\Chocolatey\lib\ssh-copy-id\tools\ssh-copy-id.cmd). This usually indicates a missing or moved file.

### UniGetUI Log

```text
Cannot find file at '..\lib\ssh-copy-id\tools\ssh-copy-id.cmd' (C:\Users\Acker Liu\AppData\Local\UniGetUI\Chocolatey\lib\ssh-copy-id\tools\ssh-copy-id.cmd).
```

### Package Managers Logs

```text
Cannot find file at '..\lib\ssh-copy-id\tools\ssh-copy-id.cmd' (C:\Users\Acker Liu\AppData\Local\UniGetUI\Chocolatey\lib\ssh-copy-id\tools\ssh-copy-id.cmd).
```

**Comment by marticliment** [comment]
Please attempt to reinstall the missing/broken package and see if it helps

**Comment by heartacker** [comment]
Cannot find file at '..\lib\ssh-copy-id\tools\ssh-copy-id.cmd' (C:\Users\Acker Liu\AppData\Local\UniGetUI\Chocolatey\lib\ssh-copy-id\tools\ssh-copy-id.cmd). This usually indicates a missing or moved file.

**Comment by heartacker** [comment]
> Please attempt to reinstall the missing/broken package and see if it helps

how

**Comment by heartacker** [comment]
It happens again
