### ISSUE TITLE
[BUG] Chinese characters cannot be display correctly

### ISSUE THREAD

**Issue by richwxd** [marticliment/UniGetUI#2523]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.1.0

### Windows version, edition, and architecture

Windows 11 Pro 23H2 22631.3880

### Describe your issue

For example, this url can be used for reproduced. Some Chinese characters display as  black blocks instead correct characters.
https://github.com/microsoft/winget-pkgs/blob/master/manifests/b/Baidu/BaiduNetdisk/7.44.0/Baidu.BaiduNetdisk.installer.yaml

### UniGetUI Log

```text
No error. just display bug
```

### Package Managers Logs

```text
No error. just display bug
```

### Screenshots and videos

<img width="656" alt="1721458915050" src="https://github.com/user-attachments/assets/edd5bb2f-ac72-4793-989a-1abcf2a64252">

**Comment by marticliment** [comment]
Please do test UniGetUI 3.1.1-beta2

**Comment by tench** [comment]
![image](https://github.com/user-attachments/assets/ec31ac42-cc47-4cc6-9e41-f95466474f6d)
Display error at 3.1.1-beta2 too.

**Comment by tench** [comment]
Sorry，I remove old version，and reinstall beta version then display is ok.
The beta version is fixed it. But  need to clean up the old version.
