### ISSUE TITLE
[BUG] Chinese package names are all garbled.

### ISSUE THREAD

**Issue by InitialXKO** [marticliment/UniGetUI#2542]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.1.0

### Windows version, edition, and architecture

Windows 11

### Describe your issue

The software package names in Chinese are all garbled.

### UniGetUI Log

```text
nothing to do with logs
```

### Package Managers Logs

```text
nothing to do with logs
```

### Screenshots and videos

![image](https://github.com/user-attachments/assets/6cbe3d27-1cfc-4d31-a05a-8effb17734a6)

**Comment by marticliment** [comment]
Please install https://github.com/marticliment/UniGetUI/releases/download/3.1.1-beta3/UniGetUI.Installer.exe
