### ISSUE TITLE
[BUG] Notifications do not depend on tray Icon, but settings UI tells otherwise

### ISSUE THREAD

**Issue by Mertsch** [marticliment/UniGetUI#2543]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.1.1.beta3

### Windows version, edition, and architecture

Windows 10

### Describe your issue

Notifications do not depend on tray Icon, but settings UI tells otherwise

### Steps to reproduce the issue

![2024-07-26 08-35-10 UniGetUI](https://github.com/user-attachments/assets/e5ad05f9-8cb4-4e7d-aa68-6c7118b8a2c9)

### Workaround
* You need to enable tray
* disable notifications
* disable tray

### UniGetUI Log

```text
Not needed
```

### Package Managers Logs

```text
Not needed
```

### Relevant information

Not needed

**Comment by marticliment** [comment]
Fixed on 41f8d4a0bae91f28a8c67e2a2e97af441e24949a

**Comment by Mertsch** [comment]
@marticliment Just a suggestion: Since Notifications work independent of the tray icon, wouldn't it make sense to allow separate configuration, rather then depending on one another?

Since I do not use them, I do not care, but someone who likes them might :-)

**Comment by marticliment** [comment]
> Since Notifications work independent of the tray icon,

That is not entirely true, some UniGeTUI features depend on the system tray, and some of the notifications will not show, hence the restriction
