### ISSUE TITLE
[BUG] `WildfireGames.0AD` not displayed despite being listed via `winget search`.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [marticliment/UniGetUI#2549]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

https://github.com/marticliment/UniGetUI/releases/download/3.1.0/UniGetUI.Installer.exe

### Windows version, edition, and architecture

Windows 11 Home

### Describe your issue

If I search for "0AD", nothing appears:

> ![image](https://github.com/user-attachments/assets/807ba46f-39b0-413c-99ef-e27430601368)

...yet `winget search '0AD'` does:

> ```log
> PS C:\Users\jared> winget search '0ad'
> Name   Id                Version      Match        Source
> ---------------------------------------------------------
> 0 A.D. WildfireGames.0AD r27104-alpha Moniker: 0AD winget
> ```

### Steps to reproduce the issue

1.	#### **UniGet**
	1.	Invoke UniGetUI.
	1.	Search "0AD".
1.	#### **WinGet**
	Invoke `winget search '0AD'`.

### UniGetUI Log

I don't have access to this yet. It's on another machine.

### Package Managers Logs

I don't have access to this yet. It's on another machine.

### Relevant information

1.	https://github.com/microsoft/winget-pkgs/tree/26c8521c3781d8cc0f85c39a4fbaa575d5506e3f/manifests/w/WildfireGames/0AD
1.	https://winget.run/pkg/WildfireGames/0AD, although that domain is usually out-of-date.

### Screenshots and videos

Aforedepicted.

**Comment by marticliment** [comment]
This issue was fixed by https://github.com/marticliment/UniGetUI/commit/b185194e08797993b2cfe6478fc9919cc2ee6e45
