### ISSUE TITLE
[ENHANCEMENT] Update README.md and CONTRIBUTING.md

### ISSUE THREAD

**Issue by skanda890** [marticliment/UniGetUI#2561]
### Please confirm these before moving forward.

- [X] I have searched for my feature proposal and have not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This improvement refers to an existing feature. If you want to suggest a new feature, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=new-feature&projects=&template=feature-request.yml&title=%5BFEATURE+REQUEST%5D+%28Enter+your+description+here%29).
- [X] This improvement is not a bug. If you want to report a bug, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=bug&projects=&template=bug-issue.yml&title=%5BBUG%5D+%28Enter+your+description+here%29).

### Describe the improvement

Update README.md and CONTRIBUTING.md

### Describe how this improvement could help users

It removes mistakes from README.md and CONTRIBUTING.md.

**Comment by marticliment** [comment]
Why create an issue?

Just create the PR

**Comment by skanda890** [comment]
> Why create an issue?
> 
> Just create the PR

#2560

For "Related to #XXXX" blank.

**Comment by marticliment** [comment]
Not required, only add it if there is an issue about it, but there is no need to create an issue for it
