### ISSUE TITLE
Compatibility with Package Managers table not displayed in main website

### ISSUE THREAD

**Issue by DegrangeM** [marticliment/UniGetUI#2590]
On the main website, the compatibility table is not displayed (which is very confusing) : 

https://www.marticliment.com/wingetui/#compat-table

**Comment by marticliment** [comment]
![image](https://github.com/user-attachments/assets/938de396-e7d2-4efb-9f8a-4e2ace25ec52)

I can see it, is it not showing for you?

**Comment by DegrangeM** [comment]
![image](https://github.com/user-attachments/assets/c117a672-d060-422d-ba38-e17cddfeeeaf)

No I don't see it on my computer (Google Chrome), but I do see it on my phone.

**Comment by DegrangeM** [comment]
This was my adblocker (ublock origin), maybe because of the class name ? "adDiv"

**Comment by jerone** [comment]
Oh wow, mine ad-blocker was also hiding this table (AdBlock Plus on Firefox).

**Comment by marticliment** [comment]
I will attempt to get this fixed.

I will rename the class in the source CSS

**Comment by marticliment** [comment]
This issue should have been fixed
