### ISSUE TITLE
[BUG] BOINC 8.0.4 Update

### ISSUE THREAD

**Issue by pwcrickman** [marticliment/UniGetUI#2592]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.1.1

### Windows version, edition, and architecture

Windows 11 Home 23H2

### Describe your issue

A new version (8.0.4) of BOINC (UCBerkeley.BOINC) was listed when I refreshed the software updates today.  I have version 8.0.2 installed.  The update failed claiming that the install technology was incompatible with the current version installed.   I visited the BOINC website and the official download is version 8.0.2.  Where is this update published?  According to the BOINC forum there has been a recent malware that downloads a rogue version of the BOINC client.

### Steps to reproduce the issue

Install BOINC version 8.0.2 and refresh the UniGetUI software updates.

### UniGetUI Log

```text
N/A
```

### Package Managers Logs

```text
N/A
```

**Comment by marticliment** [comment]
You should post this issue to `microsoft/winget-pkgs` if the package manager is WinGet, otherwhise please contact the maintainer of the package.

UniGetUI is only an interface, we do not directly manage the packages available
