### ISSUE TITLE
[ENHANCEMENT] Column to show the download size of the update

### ISSUE THREAD

**Issue by jcamp** [marticliment/UniGetUI#2601]
### Please confirm these before moving forward.

- [X] I have searched for my feature proposal and have not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This improvement refers to an existing feature. If you want to suggest a new feature, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=new-feature&projects=&template=feature-request.yml&title=%5BFEATURE+REQUEST%5D+%28Enter+your+description+here%29).
- [X] This improvement is not a bug. If you want to report a bug, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=bug&projects=&template=bug-issue.yml&title=%5BBUG%5D+%28Enter+your+description+here%29).

### Describe the improvement

Would be handy to have a column on the software updates to show the size of the download update. Some are small and quick others take a long time to download and can be waiting on an installation screen when you walk away.

### Describe how this improvement could help users

As above, helps to show the size of the download and how long it may take to download and install.

**Comment by marticliment** [comment]
I am afraid package managers do not provide this information on a fast enough source so that it can be loaded for all listed packages at the same time.
