### ISSUE TITLE
[BUG] Adding a package to the update queue more than once has issues

### ISSUE THREAD

**Issue by redactedscribe** [marticliment/UniGetUI#2606]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.1.1

### Windows version, edition, and architecture

Windows 11 Pro

### Describe your issue

If you right-click a package and choose Update, this action can be performed twice and the package will be listed twice in the queue. A package should only be allowed to be added once to the queue. If a package update was cancelled or failed, then the package should be allowed to be added to the queue again. If a package has been added to the update queue twice, the second will fail anyway.

If the above is fixed the following will probably also be fixed: Adding a package once to the update queue cause the package in the list of updates to turn grey. Adding it a second time keeps the package in the list grey. The problem happens when cancelling one of the two updates in the queue: the package in the list of updates turns to black text / normal again even though it still is in the update queue.

### UniGetUI Log

```text
-
```

### Package Managers Logs

```text
-
```

**Comment by marticliment** [comment]
Will change the behaviour of it
