### ISSUE TITLE
Inappropriate (?) Reference to 'Microsoft' in "Live Output"

### ISSUE THREAD

**Issue by MikeSW17** [marticliment/UniGetUI#2613]
### Please confirm these before moving forward.

- [X] I have searched for my feature proposal and have not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This improvement refers to an existing feature. If you want to suggest a new feature, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=new-feature&projects=&template=feature-request.yml&title=%5BFEATURE+REQUEST%5D+%28Enter+your+description+here%29).
- [X] This improvement is not a bug. If you want to report a bug, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=bug&projects=&template=bug-issue.yml&title=%5BBUG%5D+%28Enter+your+description+here%29).

### Describe the improvement

Given the re-branding of UniGet, the reference to MS not granting licences or supporting 3rd party products in "Live Output",  seems inappropriate.
Perhaps the reference should be to 'UniGet' or something more generic, or removed completely?
  

### Describe how this improvement could help users

Completing the re-branding, and avoid confusion.

**Comment by marticliment** [comment]
This is the output from WinGet cli, and it does not make sense to change it.
