### ISSUE TITLE
[FEATURE REQUEST] Multi threaded download

### ISSUE THREAD

**Issue by inschrift-spruch-raum** [marticliment/UniGetUI#2614]
### Please confirm these before moving forward.

- [X] I have searched for my feature proposal and have not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This proposal is a completely new feature. If you want to suggest an improvement or an enhancement, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=enhancement&projects=&template=enhancement-improvement.yml&title=%5BENHANCEMENT%5D+%28Enter+your+description+here%29).

### Describe the new feature

Use multi-threaded download package
1. Use multithreading for a single package
2. Use multithreading for multiple packages

### Describe how this new feature could help users

Accelerate the download and installation of packages, so that software usage is not limited by the number of packages

**Comment by marticliment** [comment]
UniGetUI does not directly handle the installation of packages, this is done by package managers, so this can't be fixed by UniGetUI
