### ISSUE TITLE
[CRASH] (Enter your description here)

### ISSUE THREAD

**Issue by CodingRookie98** [marticliment/UniGetUI#2623]
### Please confirm these before moving forward.

- [X] I have tried deleting a folder named `UniGetUI` under `%UserProfile%\AppData\Local\UniGetUI`.
- [X] I have tried reinstalling UniGetUI.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).

### Describe your crash

![image](https://github.com/user-attachments/assets/4b142e85-13f6-4ff6-82e2-8bf700f172cf)

The text in the image: "This operation only applies to the currently installed product."

When updating from version 3.0.2 to the new version, this issue occurs. How can it be resolved?

### More details

3.0.2 is the highest version I can install; any version higher than 3.0.2 causes this issue, preventing installation or update.

**Comment by marticliment** [comment]
This issue shouls have been fixed on this commit: https://github.com/marticliment/UniGetUI/commit/7e86fb81610ab71c4b50c2d7fee577bd7c25662a
