### ISSUE TITLE
[BUG] WingetUI 3.0.2 crashing when launching

### ISSUE THREAD

**Issue by makedir** [marticliment/UniGetUI#2636]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.0.2

### Windows version, edition, and architecture

Windows 11 23h2

### Describe your issue

It was working 2 weeks ago but I had not used the Pc 2 weeks, now launching it, it wont work anymore.

### Steps to reproduce the issue

Launch WingetUI 3.0.2

### UniGetUI Log

```text
Beschreibung
Name der fehlerhaften Anwendung: WingetUI.exe, Version: 1.0.0.0, Zeitstempel: 0x65cd0000
Name des fehlerhaften Moduls: Microsoft.UI.Xaml.dll, Version: 3.1.5.0, Zeitstempel: 0x7fd76c03
Ausnahmecode: 0xc000027b
Fehleroffset: 0x0000000000404495
ID des fehlerhaften Prozesses: 0x0x239C
Startzeit der fehlerhaften Anwendung: 0x0x1DAEEAD00719267
Pfad der fehlerhaften Anwendung: C:\Program Files\WingetUI\WingetUI.exe
Pfad des fehlerhaften Moduls: C:\Program Files\WingetUI\Microsoft.UI.Xaml.dll
Berichtskennung: 951590bf-638a-4d30-9601-434c40b308bb
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:
```

### Package Managers Logs

```text
-
```

**Comment by marticliment** [comment]
Please use UniGetUI 3.1.1, 3.0.2 is an old release
