### ISSUE TITLE
[BUG] Export Installed Packages Functionality No Longer Present

### ISSUE THREAD

**Issue by dabockster** [marticliment/UniGetUI#2647]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.1.1

### Windows version, edition, and architecture

Windows 11 Pro 23H2

### Describe your issue

The export button in the installed packages list referenced here[1] is no longer present since the UI refresh from WinGetUI to UniGetUI.

[1] https://www.marticliment.com/wingetui/help/import-overview/

### UniGetUI Log

```text
Not pasting due to PII present in the log.
```

### Package Managers Logs

```text
Not pasting due to PII present in the log.
```

**Comment by marticliment** [comment]
Please select packages willing to export -> "Add to package bundle" on the toolbar:

<img width="826" alt="image" src="https://github.com/user-attachments/assets/6688154f-a2e3-4478-b451-f10a1bffcbe4">

**Comment by dabockster** [comment]
Thanks! Can you update the documentation on the website with this info?

**Comment by marticliment** [comment]
I will

**Comment by BillionJothi** [comment]
Hi this issue seems to have re-occurred in 3.35

<img width="1662" height="277" alt="Image" src="https://github.com/user-attachments/assets/300e63d0-d6be-4e8b-b4b6-4b9dfd8025e3" />

**Comment by marticliment** [comment]
<img width="1665" height="300" alt="Image" src="https://github.com/user-attachments/assets/9330d87a-23c6-4d7e-9ce1-d5459c23f4a3" />

??
