### ISSUE TITLE
[BUG] Some packages keep showing up in the list in grey / cogs icon even after updating

### ISSUE THREAD

**Issue by redactedscribe** [marticliment/UniGetUI#2660]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.1.1

### Windows version, edition, and architecture

Windows 11 Pro

### Describe your issue

Since last / a few version ago, packages keep showing in the list after being updated. The issue is, I don't think they are actually updating, but UniGetUI says the update completes, but then the package appears in the list of updates next time updates are checked for, but with a cogs icon next to them rather than what is the default, and the item in greyed text rather than black. (Note that the greyed items with hourglass icons are expected as they were currently being updated, I'm speaking only of those with a cogs icon next to them.)

As you can see in the screenshot below, the packages which are greyed out but apparently can be updated usually return some live output like:

```
dolphin-beta: 5.0-21460 (latest version)
Latest versions for all apps are installed! For more information try 'scoop status'
```

Or:

```
-
███████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  1024 KB / 2.64 MB
██████████████████████▒▒▒▒▒▒▒▒  2.00 MB / 2.64 MB
\
No available upgrade found.
No newer package versions are available from the configured sources.
```

Or:

```
odin: 2024-07 -> 2024-08
Updating one outdated app:
Updating 'odin' (2024-07 -> 2024-08)
Downloading new version
Loading odin-windows-amd64-dev-2024-08.zip from cache
Checking hash of odin-windows-amd64-dev-2024-08.zip ... ok.
Uninstalling 'odin' (2024-07)
Unlinking D:\Scoop\apps\odin\current
Installing 'odin' (2024-08) [64bit] from 'versions' bucket
Loading odin-windows-amd64-dev-2024-08.zip from cache
Extracting odin-windows-amd64-dev-2024-08.zip ... done.
Linking D:\Scoop\apps\odin\current => D:\Scoop\apps\odin\2024-08
Creating shim for 'odin'.
Can't shim 'odin.exe': File doesn't exist.
```

As seen in the logs below, the default icon is being used ("returning default icon") which is the cogs icon presumably. But normally, packages have the package / box icon. 
![Icon_2024-08-24_12-47-07](https://github.com/user-attachments/assets/796a5747-262a-4252-a4c3-2a33b5e764f3)

### Steps to reproduce the issue

-

### UniGetUI Log

```text
...
[23/08/2024 17:48:00] Icon for package odin was not found, returning default icon
[23/08/2024 17:48:02] Icon for package dolphin-beta was not found, returning default icon
[23/08/2024 17:48:13] Loaded icon with URL=UniGetUI.Core.IconEngine.CacheableIcon for package Id=smartgit
[23/08/2024 17:48:13] Icon for package smartgit stored on C:\Users\User\AppData\Local\UniGetUI\CachedMedia\Scoop\smartgit.png
[23/08/2024 17:48:17] Non-MSStore WinGet Native Icons have been forcefully disabled on code
[23/08/2024 17:48:17] Icon for package spacedrive.Spacedrive was not found, returning default icon
[23/08/2024 17:48:19] Non-MSStore WinGet Native Icons have been forcefully disabled on code
...
```

### Package Managers Logs

Could only find 2 errors in the package manager logs:

```text
Logged subprocess-based task on manager Npm. Task type is ListUpdates
Subprocess executable: "C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe"
Command-line arguments: " -NoProfile -ExecutionPolicy Bypass -Command npm outdated --parseable"
Process start time: 24/08/2024 12:30:19
Process end time:   24/08/2024 12:30:24

-- Process STDOUT
 ...

Return code: FAILED (1)

——————————————————————————————————————————

...

——————————————————————————————————————————

Logged subprocess-based task on manager Npm. Task type is ListInstalledPackages
Subprocess executable: "C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe"
Command-line arguments: " -NoProfile -ExecutionPolicy Bypass -Command npm list --global"
Process start time: 24/08/2024 12:48:42
Process end time:   UNFINISHED

Return code: Process has not finished yet
```

### Screenshots and videos

![UniGetUI_2024-08-24_12-34-05](https://github.com/user-attachments/assets/2b0e8d62-eaa3-45a0-ae76-10b56fd0b628)

**Comment by marticliment** [comment]
Will investigate
