### ISSUE TITLE
[BUG] Runtime Error 40:328

### ISSUE THREAD

**Issue by CodeAru** [marticliment/UniGetUI#2664]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.1.1

### Windows version, edition, and architecture

Windows 10 Pro 21H2

### Describe your issue

![runtime error](https://github.com/user-attachments/assets/5c0bdc4c-ad96-466c-b7cd-c5b649f512c6)

I've had WinGetUI 3.0.2 for a long time but the update to the latest version had always failed.
I ended up uninstalling WinGetUI through Revo Uninstaller and made sure there were no leftovers but I still cannot install the latest version due to the Runtime Error 40:328

![Capture](https://github.com/user-attachments/assets/c5d922ab-6633-4873-9b74-99cbc34448ba)

Just in case I've made sure I had some dependencies might have been installed but I'm totally drawing a blank here...

### UniGetUI Log

```text
-
```

### Package Managers Logs

```text
-
```

**Comment by marticliment** [comment]
I will investigate

**Comment by CodeAru** [comment]
Hello.

I apologize about delay, it was a busy week. I have just tried installing the new version, but after the language selection screen literally nothing happens.

**Comment by CodingRookie98** [comment]
@CodeAru I also encountered the same problem.

**Comment by CodingRookie98** [comment]
> Hello.
> 
> I apologize about delay, it was a busy week. I have just tried installing the new version, but after the language selection screen literally nothing happens.

3.1.2 bata 1 also has the same problem

**Comment by marticliment** [comment]
Like it just closes and does nothing?

**Comment by CodeAru** [comment]
> Like it just closes and does nothing?

Hello, yes. Precisely that's what happens.

**Comment by CodingRookie98** [comment]
> Like it just closes and does nothing?

![image](https://github.com/user-attachments/assets/d9ee8113-c5c6-4e31-9e1e-bfdac5c5a726)
Yes, nothing happens after this dialog.

**Comment by marticliment** [comment]
I will investigate, it is really weird

**Comment by AmigaTronik2024** [comment]
Hi, I Have exactly the same problem,  "Runtime Error 40:328" & Closes after "Setup Language"
with beta (3.1.2-beta0) I Have had this problem since 3.1.0 Alpha0 version & upwards.

Thanks,

**Comment by vgisbert** [comment]
I have the same problem

**Comment by marticliment** [comment]
Please test this release:
https://github.com/marticliment/UniGetUI/releases/tag/3.1.2-beta2

**Comment by vgisbert** [comment]
3.1.2 beta 1, also has the same problem.

**Comment by marticliment** [comment]
no this is beta 2

**Comment by vgisbert** [comment]
Beta 2 is OK (SORRY)

**Comment by marticliment** [comment]
Can this issue be considered fixed then?

**Comment by CodeAru** [comment]
> Can this issue, then, be considered fixed?

Hi, the issue has been fixed. Thank you!

**Comment by AmigaTronik2024** [comment]
Yes, Issue has been fixed, 

Good work Marti 👍

Mouse wheel for scrolling is broken though in this release. "**3.1.2-beta2**" Well it has at my end.
