### ISSUE TITLE
[BUG] Shows PowerShell source code instead of package information

### ISSUE THREAD

**Issue by MovGP0** [marticliment/UniGetUI#2675]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.1.1

### Windows version, edition, and architecture

Windows 11 Pro (22631)

### Describe your issue

There is PowerShell code instead of package information for PowerShell module updates. (see screenshots)

### UniGetUI Log

```text
none
```

### Package Managers Logs

```text
none
```

### Screenshots and videos

![image](https://github.com/user-attachments/assets/87e96ae1-f3f5-439b-ba5b-d9862e650ebb)

![image](https://github.com/user-attachments/assets/d4bd444f-1fc6-4883-919e-ce27b47376ad)

**Comment by marticliment** [comment]
Please share your PowerShell 7.x package manager logs

**Comment by marticliment** [comment]
Is this issue still present on UniGetUI 3.1.3?

**Comment by MovGP0** [comment]
I cannot reproduce it in the current version. So I assume it is fixed. Thanks!
