### ISSUE TITLE
[BUG] codepage parsing fails in other locales

### ISSUE THREAD

**Issue by Bananeweizen** [marticliment/UniGetUI#2676]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.1.1

### Windows version, edition, and architecture

Win11 German

### Describe your issue

The string manipulation for getting the codepage settings via external process doesn't work with German language setting. The output of the process is "Aktive Codepage: 850." Note the trailing dot. Instead of splitting and trimming, I suggest matching the string with the regex "\d+", which will return the first continuous sequence of digits.

### UniGetUI Log

```text
System.FormatException: The input string '850.' was not in a correct format.
         at System.Number.ThrowFormatException[TChar](ReadOnlySpan`1 value)
         at System.Int32.Parse(String s)
         at UniGetUI.Core.Data.CoreData.GetCodePage() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.Core.Data\CoreData.cs:line 26
```

### Package Managers Logs

```text
-
```

**Comment by marticliment** [comment]
I just fixed this two days ago on d3f18bc0a94ba17a371ac01a584ab950a1fced79
