### ISSUE TITLE
Why does UniGetUI update from 3.1.0 to 3.1.1 fail if it takes more than 100 seconds if the internet speed is slow?

### ISSUE THREAD

**Issue by candrapersada** [marticliment/UniGetUI#2720]
Back when it was still called `WingetUI`, automatic updates never failed because there was no time limit and it could update without failing because there was no 100 second time limit at that time.

**Comment by marticliment** [comment]
What is failing? You need to provide more details

**Comment by marticliment** [comment]
Huh, I will investigate

**Comment by candrapersada** [comment]
why the 100 seconds issue still exists when updating from 3.1.2 to 3.1.3 if the download speed is slow?

**Comment by marticliment** [comment]
I tested the issue and for me it was solved, I will investigate

**Comment by candrapersada** [comment]
![image](https://github.com/user-attachments/assets/d8874f9e-97af-4a34-b31f-bda037e2c229)
