### ISSUE TITLE
[BUG]  scoop install 3.1.1 failure, but 3.0.2 success

### ISSUE THREAD

**Issue by zuilintan** [marticliment/UniGetUI#2722]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.1.1

### Windows version, edition, and architecture

Windows 11 Enterprise 24H2

### Describe your issue

scoop install 3.1.1 failure, but 3.0.2 success.
![image](https://github.com/user-attachments/assets/c70fb159-bb29-453c-960b-1c4d3c7004f1)

scoop log: 
```
Signature detected: Inno Setup Setup Data (6.3.0)
This is not directly supported, but i'll try to unpack it as version 5602
; Version detected: 6300
Critical error: The setup files are corrupted. Please obtain a new copy of the program.
```

### UniGetUI Log

```text
PS C:\Users\LinTan> scoop install wingetui
Installing 'wingetui' (3.1.1) [64bit] from 'extras' bucket
WingetUI.Installer.exe (51.2 MB) [============================================================================] 100%
Checking hash of WingetUI.Installer.exe ... ok.
Extracting WingetUI.Installer.exe ... ERROR Exit code was 1!
Failed to extract files from C:\Users\LinTan\scoop\apps\wingetui\3.1.1\WingetUI.Installer.exe.
Log file:
  ~\scoop\apps\wingetui\3.1.1\innounp.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Extras/issues/new?title=wingetui%403.1.1%3a+decompress+error
PS C:\Users\LinTan> scoop uninstall wingetui
ERROR 'wingetui' isn't installed correctly.
```

### Package Managers Logs

```text
~
```

**Comment by marticliment** [comment]
I am not the maintainer of the scoop package, so I can't help with that.

**Comment by zuilintan** [comment]
Thanks，Resolved。
https://github.com/ScoopInstaller/Main/issues/6201#issuecomment-2375220784
