### ISSUE TITLE
[BUG] Can't stay on stable version of UniGetUI

### ISSUE THREAD

**Issue by patrick-5546** [marticliment/UniGetUI#2727]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.1.2-beta1

### Windows version, edition, and architecture

Windows 11 Home

### Describe your issue

When I install the stable version `SomePythonThings.WingetUIStore`, UnigetUI automatically detects itself to be the pre release version `SomePythonThings.WingetUIStore.Pre-release` and updates to the latest prerelease version

### UniGetUI Log

```text
n/a
```

### Package Managers Logs

```text
n/a
```

**Comment by marticliment** [comment]
duplicate of #2710

Please right-click -> skip this version.
