### ISSUE TITLE
[IMPROVEMENT] Change UniGetUI package id in WinGet

### ISSUE THREAD

**Issue by ghost** [marticliment/UniGetUI#2736]
### Please confirm these before moving forward.

- [X] I have searched for my feature proposal and have not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This improvement refers to an existing feature. If you want to suggest a new feature, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=new-feature&projects=&template=feature-request.yml&title=%5BFEATURE+REQUEST%5D+%28Enter+your+description+here%29).
- [X] This improvement is not a bug. If you want to report a bug, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=bug&projects=&template=bug-issue.yml&title=%5BBUG%5D+%28Enter+your+description+here%29).

### Describe the improvement

Currently UniGetUI has the old name in the Winget package listing:

![winget](https://github.com/user-attachments/assets/07d87a4c-da24-4296-8dfa-eef0996b3417)

Not only that, UniGetUI is published under a totally strange id, with no relation to the author or the programming language used (which seems to be C#):
`SomePythonThings.WingetUIStore`

The package id should be changed to some options like:
```
MartiCliment.UniGetUI
MartiCliment.UniGetUIStore
```

Anyone searching for WingetUI would still find UniGetUI because the package name mentions the old name "(formerly WingetUI)".

### Describe how this improvement could help users

It helps improve the classification, identification and location of the package, as the id is correctly assigned to the author and directory name on github and the official website:
1. https://github.com/marticliment/UniGetUI/
2. https://www.marticliment.com/unigetui/

**Comment by marticliment** [comment]
Yes, but can an Id be changed in WinGet?

**Comment by MRDGH2821** [comment]
@marticliment I think it is indeed possible
https://learn.microsoft.com/en-us/windows/package-manager/package/

And I see a recent commit made here too - https://github.com/microsoft/winget-pkgs/commit/1d077a47171e02b6b468bd74af2b7f3c05a85b54

**Comment by marticliment** [comment]
Yes yes this is a thing that is being worked on. The migration should be done in the following days.

More details here: https://github.com/microsoft/winget-pkgs/issues/174102
