### ISSUE TITLE
[BUG] GH update is always failing

### ISSUE THREAD

**Issue by skanda890** [marticliment/UniGetUI#2739]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.1.2 beta1

### Windows version, edition, and architecture

Windows11 Pro 22621.4169

### Describe your issue

GH update is always failing.

### Steps to reproduce the issue

Try to update gh:
![image](https://github.com/user-attachments/assets/688033ff-3f66-41f4-a5aa-19531350ab26)

### Relevant information

Command line output:

```powershell
Starting package update operation for package id=gh with Manager name=Chocolatey
Given installation options are <InstallationOptions: SkipHashCheck=False;InteractiveInstallation=False;RunAsAdministrator=False;Version=;Architecture=;InstallationScope=;InstallationScope=;CustomParameters=;RemoveDataOnUninstall=False>
Process Executable     : C:\Users\Skand_zncmqfh\AppData\Local\UniGetUI\Chocolatey\bin\choco.exe
Process Call Arguments :  upgrade gh -y --no-progress
Working Directory      : C:\Users\Skand_zncmqfh
Process Start Time     : 14-09-2024 12:39:40
    | Chocolatey v2.2.2
    | Chocolatey detected you are not running from an elevated command shell
    |  (cmd/powershell).
    |  You may experience errors - many functions/packages
    |  require admin rights. Only advanced users should run choco w/out an
    |  elevated shell. When you open the command shell, you should ensure
    |  that you do so with "Run as Administrator" selected. If you are
    |  attempting to use Chocolatey in a non-administrator setting, you
    |  must select a different location other than the default install
    |  location. See
    |  https://docs.chocolatey.org/en-us/choco/setup#non-administrative-install
    |  for details.
    | For the question below, you have 20 seconds to make a selection.
    |  Do you want to continue?([Y]es/[N]o): 
    | Timeout or your choice of '﻿' is not a valid selection.
    | gh
    | By upgrading, you accept licenses for the packages.
    | You have gh v2.52.0 installed. Version 2.56.0 is available based on your source(s).
    | gh v2.56.0 [Approved]
    | gh package files upgrade completed. Performing other installation steps.
    | Installing 64-bit gh...
    | WARNING: Installation of this MSI is forbidden by system policy. Please contact your system administrators.
    | ERROR: Running ["C:\WINDOWS\System32\msiexec.exe" /i "C:\Users\Skand_zncmqfh\AppData\Local\UniGetUI\Chocolatey\lib\gh\tools\gh_2.56.0_windows_amd64.msi" /qn /norestart /l*v "C:\Users\Skand_zncmqfh\AppData\Local\Temp\chocolatey\gh-2.56.0-MsiInstall.log" ] was not successful. Exit code was '1625'. Exit code indicates the following: Installation of this MSI is forbidden by system policy. Please contact your system administrators..
    | The upgrade of gh was NOT successful.
    | Error while running 'C:\Users\Skand_zncmqfh\AppData\Local\UniGetUI\Chocolatey\lib\gh\tools\chocolateyInstall.ps1'.
    |  See log for details.
    | Chocolatey upgraded 0/1 packages. 1 packages failed.
    |  See the log for details (C:\Users\Skand_zncmqfh\AppData\Local\UniGetUI\Chocolatey\logs\chocolatey.log).
    | Failures
    |  - gh (exited 1625) - Error while running 'C:\Users\Skand_zncmqfh\AppData\Local\UniGetUI\Chocolatey\lib\gh\tools\chocolateyInstall.ps1'.
    |  See log for details.
Process Exit Code      : 1625
Process End Time       : 14-09-2024 12:40:21
```

### Screenshots and videos

Step 1: ![image](https://github.com/user-attachments/assets/6f406b39-bdbb-40f3-80ed-e961de61d41f)
Step 2: ![image](https://github.com/user-attachments/assets/158ab9f6-d31a-4ae5-8bc2-6bc4feb32796)

**Comment by skanda890** [comment]
### UniGet UI Logs: [UniGetUI Log.txt](https://github.com/user-attachments/files/17001437/UniGetUI.Log.txt)

### Package Manager Logs: [Package Manager Logs.txt](https://github.com/user-attachments/files/17001438/UniGetUI.Log.P.txt)

**Comment by marticliment** [comment]
I am afraid this issue is caused by your system consiguration, and not by UniGetUI
![image](https://github.com/user-attachments/assets/8ee3a006-091b-485f-b6e2-dbd55003471c)

**Comment by skanda890** [comment]
How can I fix this?

**Comment by marticliment** [comment]
I don't know, you should google how to enable msi installations from group policy. It is possible to face this issues when using ntreprise/school managed devices
