### ISSUE TITLE
[BUG] Fix software update when old MSI installer is missing (MSI exit code 1603)

### ISSUE THREAD

**Issue by kitlei-robert** [marticliment/UniGetUI#2742]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.1.2-beta1

### Windows version, edition, and architecture

Windows 11 22631.4169

### Describe your issue

**Summary**: updating (more properly, "upgrading") a software package should only require the installer of the new version, but unfortunately, the old installer is also essential to be present. If it is not, automated installation fails. (In case of an interactive installation, a modal window pops up that allows you to point to it.)

Let's assume that the software in question is LibreOffice. We've got version 24.8.0 installed, the version to be installed is 24.8.1. (The same happens during upgrading Rust, Pandoc and possibly many more that use a standard MSI installer.)

**Expected behaviour**: LibreOffice 24.8.0 is uninstalled, then 24.8.1 is installed in one go.

**What actually happens**: during the uninstallation phase of the old version 24.8.0, the MSI Installer (in this case, `LibreOffice_24.8.1_Win_x86-64.msi`) detects that it cannot find the old installer (`libreOffice_24.8.0_Win_x86-64.msi`). UniGetUI installation fails. The user is forced to manually install the new version, which totally defeats the primary purpose of UniGetUI. Worse, the user is not properly informed about what's wrong.

As the process of upgrading breaks down unexpectedly, I classify this failure as a **bug**. Technically, though, fixing it will require some new code to be added rather than fixing some existing code, so you may also consider it a *borderline feature request*.

**Short term fix.**
- Have UniGetUI detect the problem with the missing `.msi` file.
- Display an error message that is helpful to the user, and explains why the upgrade process failed.

**Long term fix: what UniGetUI is actually expected to do if this occurs.**
1. Do not stop the UniGetUI installation process.
1. Rather, detect that the MSI installer failed with error code `1603`.
    - This error code may possibly indicate other sorts of failure. Make sure that the actual cause is a missing `.msi` installer file.
    - If it is known that the package is installed via the MSI mechanism, you can also pre-check for the existence of the required file, and preemptively download it if you find it missing. See the last bullet point about optimisation.
1. Find out the package name of the missing, old installer. I expect this to be easy in most cases. If it cannot be determined, output an appropriate error message and stop. Supposing it's found...
1. Find out if there is enough space to download it. Supposing there is...
1. Download it.
1. Start the new version's installer again.
1. The installer should be happy as a clam now, and actually do what it's meant to in the first place: get rid of the old version, setup the new one.
1. Housekeeping: remove the old installer's file.
1. However, keep the new installer, as it will be required for the next upgrade process down the line.
    - Or, as UniGetUI is now capable of redownloading it, remove it to save the user some disk space; perhaps have this as an option.
    - As an optimisation, if many packages are to be installed/upgraded, at the beginning try to detect if there are some missing `.msi` files. Delay upgrading those packages, and while others are being installed, the missing files can be downloaded in the background, saving the user some time.

### Steps to reproduce the issue

1. Using UniGetUI or by other means, install an older version of LibreOffice (or just about anything that uses a standard MSI Installer), say 24.8.0.
2. Make sure that the old installer `.msi` file is not present at its old location. (In an actual system, cleanups will remove such files.)
3. Using UniGetUI, attempt upgrading to a newer version of LibreOffice, say 24.8.1.

### UniGetUI Log

```text
Starting package update operation for package id=TheDocumentFoundation.LibreOffice with Manager name=Winget
Given installation options are <InstallationOptions: SkipHashCheck=False;InteractiveInstallation=False;RunAsAdministrator=False;Version=;Architecture=;InstallationScope=;InstallationScope=;CustomParameters=;RemoveDataOnUninstall=False>
Process Executable     : C:\Users\user\AppData\Local\Microsoft\WindowsApps\winget.exe
Process Call Arguments :  update --id "TheDocumentFoundation.LibreOffice" --exact --source winget --accept-source-agreements --disable-interactivity --silent --include-unknown --accept-package-agreements --force
Working Directory      : C:\Users\user
    |    - 
    | Found LibreOffice [TheDocumentFoundation.LibreOffice] Version 24.8.1.2
    | This application is licensed to you by its owner.
    | Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
    | Successfully verified installer hash
    |    / 
    | Installer failed with exit code: 1603
    | Installer log is available at: C:\Users\user\AppData\Local\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir\WinGet-TheDocumentFoundation.LibreOffice.24.8.1.2-2024-09-15-03-17-59.731.log
Process Exit Code      : -1978335159
Process End Time       : 2024. 09. 15. 3:18:20
```

### Package Managers Logs

```text
(Nothing relevant stands out. All tasks and subprocesses report success with code 0, but the upgrade process as described above is anything but.)
```

### Relevant information

The log file shows a (localised) version of the following:

**Error message**: `The older version of <software> cannot be removed.  Contact your technical support group.`

Error codes that crop up are 1714, 1612, and exit code 1603. I guess the first two are internal to some unidentified source, and the third one is the MSI Installer complaining about the missing file.

**Comment by marticliment** [comment]
Does this issue also happen with winget.exe?

**Comment by kitlei-robert** [comment]
Yes, e.g. from Powershell Preview 7.5.0.3 to 7.5.0.4:

```
>winget install Microsoft.Powershell.Preview
Found an existing package already installed. Trying to upgrade the installed package...
Found PowerShell Preview [Microsoft.PowerShell.Preview] Version 7.5.0.4
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Successfully verified installer hash
Starting package install...
Installer failed with exit code: 1603
Installer log is available at: C:\Users\user\AppData\Local\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir\WinGet-Microsoft.PowerShell.Preview.7.5.0.4-2024-09-15-16-54-20.570.log
```

Running the `PowerShell-7.5.0-preview.4-win-x64.msi` installer interactively, it does indeed ask for `PowerShell-7.5.0-preview.3-win-x64.msi` as expected. This deplorable thing seems to be standard for the MSI installation mechanism, and it would be great if UniGetUI handled it as it should have been from the get-go: upgrading the package version without the need for tedious manual hunting for deprecated (un)installers.

**Comment by marticliment** [comment]
Then I am afraid you should post this issue on microsoft/winget-cli, since UniGetUI just calls winget.exe to perform the install/upgrade/uninstall jobs...
