### ISSUE TITLE
[BUG] Installer error 225

### ISSUE THREAD

**Issue by CanePlayz** [marticliment/UniGetUI#2748]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.2.1 beta 2

### Windows version, edition, and architecture

Windows 11 Home 27695

### Describe your issue

When I try to install UnigetUI, I get the issue from the screenshot below.

### Steps to reproduce the issue

Try to install UnigetUI 3.2.1 beta 2 on a Windows Arm machine (in my case, the Surface Pro 11 with the Snapdragon X Elite).

### UniGetUI Log

```text
No log as it's an issue with the installer
```

### Package Managers Logs

```text
No log as it's an issue with the installer
```

### Relevant information

I'm curious if that's an issue on my side or if it's a general issue with ARM devices, so any feedback from other ARM users would be very helpful.

### Screenshots and videos

![image](https://github.com/user-attachments/assets/996e669c-7594-453d-9eff-69baeb81b579)

**Comment by marticliment** [comment]
Are you running any AV?

**Comment by CanePlayz** [comment]
Yeah, it does seem to be related to that. When I download 3.2.1 beta 2 in Edge, I get a prompt that the file is not safe and I have to manually let the download happen. Also, when I try to start it, I get another warning. However, when I try to install for example 3.1.0, it works fine. I was able to trace it back to 3.1.2 beta 0 being the first version that Windows reports as insecure. My issues seems to be resolved now, but probably worth it to report the files as safe to Microsoft.

**Comment by marticliment** [comment]
I am afraid latest beta releases are not digitally signed, this was stated on the release notes. 

Just stay on stable until next stable comes out. Next stable will be signed

**Comment by CanePlayz** [comment]
Ahh thanks, my bad
