### ISSUE TITLE
[BUG] right click on uniget icon in taskbar will show the context menu on the other screen

### ISSUE THREAD

**Issue by axelrathey** [marticliment/UniGetUI#2775]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.1.2-beta1

### Windows version, edition, and architecture

Windows 11 Pro

### Describe your issue

When rigth clicking on unigetui icon on taskbar the context menu will often opens on the other screen. Background is that I'm using my notebook on a dock with 2 other screens. So I have 3 Screens (notebookscreen and 2 screens). Sometimes I don't think about it and wondering where the context menu is, after right clicking the icon.
Normaly I would prefer the context menu will oben on the same screen, where I clicked right the mouse.
Thanks Axel

### Steps to reproduce the issue

Use more the one screen, extend display to the second or third display screen. Right click on the unigetui icon on taskbar.

### UniGetUI Log

```text
there ist not log about it
```

### Package Managers Logs

```text
there ist not log about it
```

**Comment by marticliment** [comment]
Could you please share a screenshot/recording of the issue?

Thanks!

**Comment by axelrathey** [comment]
Hi Marti,
here the screenshot.
![Zwischenablage_09-25-2024_01_unigetUI](https://github.com/user-attachments/assets/9e87f61b-850c-4a26-86f7-4ad97a9dc7d7)

When I right click the wingetui icon on the taskbar on the middle screen the menu will open on the middle screen.
When I right click it on the right screen the menu opened on the right screen.

**But, when I right click it on the left screen the menu opened on the right screen.**

The Thunderbolt 4 USB-C Dock I'm using to connect the external screens is a DELL WD22TB4 on a DELL Notebook. The middle screen is the notebook

Thanks Axel

**Comment by marticliment** [comment]
Hello Axel,

You have a modded taskbar, right? System tray icons do not usually show on all monitors

**Comment by axelrathey** [comment]
Taskbar was configured in german Windows 11 as follows:

"Einstellungen" => "Personalisierung" =>"Taskleiste" => "Verhalten der Taskleiste" => "Meine Taskleiste auf allen Anzeigegeräten anzeigen" => "Wenn mehrere Bildschirme verwendet werden, meine Taskleisten-Apps anzeigen auf":  "Alle Taskleisten".

I don't know, how all the options are named in english Windows 11 Pro.

Thanks Axel

**Comment by marticliment** [comment]
Still, you are not supposed to see the tray icons on all the monitors: 
![image](https://github.com/user-attachments/assets/71aef96b-695b-4a06-aba4-72ced3ab0cf5)

**Comment by axelrathey** [comment]
Sorry, I don't remember how I get the taskbar with the system-tray on all screens. Here is my configuration of the task bar.

![grafik](https://github.com/user-attachments/assets/64253627-4e54-4ace-8949-4276460adf0f)

**Comment by marticliment** [comment]
I am sorry, but I can't help with that. System tray is handled by an external library (https://github.com/HavenDV/H.NotifyIcon), so I don't have any real control on it, and even then the configuration you have on your system is not even supposed to be possible to achieve.
