### ISSUE TITLE
[BUG] Microsoft Defender Antivirus found a "Trojan:Win32/Wacatac.B!ml"

### ISSUE THREAD

**Issue by 7wells** [marticliment/UniGetUI#2779]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.1.1 or 3.1.2 beta 2

### Windows version, edition, and architecture

Windows 11 Pro 23H2 22631.4169

### Describe your issue

Hello!

Microsoft Defender Antivirus found a "[Trojan:Win32/Wacatac.B!ml](https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3AWin32%2FWacatac.B!ml&threatid=2147735505)" in file `C:\Users\<myusername>\AppData\Local\Temp\is-PRUC8.tmp\UniGetUI.Installer.tmp` and eliminated the file on 18 Sep 2024. Unfortunately, I saw the message only today.

Currently, I use `UniGet 3.1.1`, but I had temporarily used `Uniget 3.1.2 beta 2` instead for 1-2 days. Whether it was on that 18 Sep, I don't remember.

I cannot provide more information at the moment, because the aforementioned folder/file are no longer available, and I don't remember which app I installed or updated at that time.

Is it a false positive? Is there anything else I could check and provide here?

Kind regards
7wells

### Steps to reproduce the issue

NA (as I can't and would't want to reproduce this)

### UniGetUI Log

```text
NA (as the log does not include the aforementioned date)
```

### Package Managers Logs

```text
NA (as the log does not include the aforementioned date)
```

### Relevant information

None

### Screenshots and videos

None

**Comment by marticliment** [comment]
Next UniGetUI versions will have all .dlls signed, so this shouldn't happen anymore. Please stick with 3.1.1, which is also signed and should not be flagged. If it is flagged, please report the false positive. Beta releases are not signed and are more lineky to be flagged as viruses (false-positives)
