### ISSUE TITLE
[FEATURE REQUEST] Default download location

### ISSUE THREAD

**Issue by cauamachado51** [marticliment/UniGetUI#2790]
### Please confirm these before moving forward.

- [X] I have searched for my feature proposal and have not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This proposal is a completely new feature. If you want to suggest an improvement or an enhancement, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=enhancement&projects=&template=enhancement-improvement.yml&title=%5BENHANCEMENT%5D+%28Enter+your+description+here%29).

### Describe the new feature

in the settings define the location where you download the installers.

### Describe how this new feature could help users

Don't destroy your C drive (SSD) by writing too much data to it.

**Comment by marticliment** [comment]
I am afraid I misunderstood what this request was for.
Default download location cannot be changed, since the download process is handled by the package manager itself and not by UniGetUI.
