### ISSUE TITLE
The procedure entry point could not be located in the dynamic link library

### ISSUE THREAD

**Issue by AronSter** [marticliment/UniGetUI#2806]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.1.1

### Widgets for UniGetUI Version

3.1.1

### Windows version, edition, and architecture

Window 10 Pro 1803 17133.1 x64

### Describe your issue

So I am facing this problem and cannot find a way to fix it. It happens after finishing the setup process.

### Steps to reproduce the issue

N/A

### UniGetUI Log

```text
N/A
```

### Package Managers Logs

```text
N/A
```

### Relevant information

N/A

### Screenshots and videos

<img width="306" alt="UniGetUI Installer tmp_LhyuwQvUfe" src="https://github.com/user-attachments/assets/dd3007f9-ea80-4b1e-ad2a-68c4d8f324b5">

**Comment by marticliment** [comment]
You are using a very old Windows 10 release. Windows 10 10.0.19041 x64 or higher
