### ISSUE TITLE
[BUG] The language I have translated long back in Tolgee still did not come in README.md

### ISSUE THREAD

**Issue by skanda890** [marticliment/UniGetUI#2827]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### Describe your issue

In the Readme.md of this repo, the language I translated long back in Tolgee still didn't show.

### Steps to reproduce the issue

Go to Readme.md of this repo, and compare it with Tolgee.

**Comment by skanda890** [comment]
> Changes will take 24/48h to be reflected from now.
> 
> Languages only show when they are over 0% on translation, which has been the situation until today

I did changes like 2-3 weeks ago.

**Comment by skanda890** [comment]
> > Changes will take 24/48h to be reflected from now.
> > 
> > Languages only show when they are over 0% on translation, which has been the situation until today
> 
> I did changes like 2-3 weeks ago.

But still I didn't come in Readme.md.

**Comment by marticliment** [comment]
Changes should have already been applied by now

**Comment by skanda890** [comment]
You put the wrong flags, both should be flagcdn.com/in.svg

**Comment by marticliment** [comment]
The flags show fine for me

**Comment by skanda890** [comment]
> The flags show fine for me

Kannada and Sanskrit are majorly spoken in India. So, put the Indian flag.

**Comment by marticliment** [comment]
Yes, the indian flag shows on both languages, doesn't it?
