### ISSUE TITLE
[BUG] In German some Words on the left are broken

### ISSUE THREAD

**Issue by Richiebaer** [marticliment/UniGetUI#2843]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.1.2 beta4

### Windows version, edition, and architecture

Windows 11 Pro 22635.4367

### Describe your issue

In German some Words on the left are broken (Einstellungen = Settings).

![image](https://github.com/user-attachments/assets/88cd6d93-1352-43d2-b6d4-4921520d8b3e)

### UniGetUI Log

```text
-
```

### Package Managers Logs

```text
-
```

**Comment by marticliment** [comment]
Did this happen in 3.1.1?

**Comment by Richiebaer** [comment]
No, only on 3.1.2 beta 2 and up. The column seems to short.

**Comment by Daviteusz** [comment]
![obraz](https://github.com/user-attachments/assets/fb8601b5-6631-4da1-abae-3358a759490f)
+1
