### ISSUE TITLE
[FEATURE REQUEST] Download while Installing

### ISSUE THREAD

**Issue by Silvenga** [marticliment/UniGetUI#2845]
### Please confirm these before moving forward.

- [X] I have searched for my feature proposal and have not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This proposal is a completely new feature. If you want to suggest an improvement or an enhancement, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=enhancement&projects=&template=enhancement-improvement.yml&title=%5BENHANCEMENT%5D+%28Enter+your+description+here%29).

### Describe the new feature

It would be neat if UniGet could, when upgrading many packages, download other installers while installing/upgrading the current installer.

With WinGet, the download command could be used - https://learn.microsoft.com/en-us/windows/package-manager/winget/download. WinGet already uses any existing cached downloads when installing.

An alternative could be to download installers in the background with the same download command, and install like normal when given user consent.

### Describe how this new feature could help users

This is similar to how the Visual Studio installer can download while installing, vastly increasing the speed of upgrades.

**Comment by marticliment** [comment]
I am afraid this does not work the way you say it does:
![image](https://github.com/user-attachments/assets/e6fa581c-66ba-4907-abcb-5e7243fe4edf)

Furthermore, it would only work with WinGet

**Comment by Silvenga** [comment]
Damn, you're right. Sorry about not testing that first.

It's been a long term request on the WinGet side, I thought they actually implemented the download command like everyone has been asking for, but no, it went a completely different direction 😹

I guess UniGet could download and then directly install, but that get's really hairy, very quickly.
