### ISSUE TITLE
[BUG] UniGetUI won't install on Windows 10 ARM64

### ISSUE THREAD

**Issue by RonnyTNL** [marticliment/UniGetUI#2851]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.1.1 / 3.1.2b4

### Windows version, edition, and architecture

Windows 10 Home - ARM64

### Describe your issue

When trying to Install UniGetUI on AMR64 Window 10 Home the install works but starting the application fails.
This does however work on Windows 11 of the same hardware.

With other software you need to pick the x86 version for Win10 ARM64 and x64 for Win11 ARM64 perhaps the installer drops the x64 build on Win10 ARM64?

### Steps to reproduce the issue

Install UniGetUI either via installer or WinGet CLI.
Installer works but once the installer tries to spawn the applicaton it fails, WinGet bails with "no applicable installer found".

![image](https://github.com/user-attachments/assets/7311cc11-a58c-441f-a451-d62744fd2ce9)

![image](https://github.com/user-attachments/assets/ae8d01c7-0a77-483a-a2cb-6ef767ff48ce)

### UniGetUI Log

```text
N/A
```

### Package Managers Logs

```text
N/A
```

**Comment by marticliment** [comment]
Windows 10 Arm64 is not supported.
Supported OS:
 - Windows 10 x64 
 - Windows 11 x64
 - Windows 11 arm64 (through x64 emulation)
