### ISSUE TITLE
[FEATURE REQUEST] Cache Install Packages on LAN

### ISSUE THREAD

**Issue by desi76** [marticliment/UniGetUI#2854]
### Please confirm these before moving forward.

- [X] I have searched for my feature proposal and have not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This proposal is a completely new feature. If you want to suggest an improvement or an enhancement, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=enhancement&projects=&template=enhancement-improvement.yml&title=%5BENHANCEMENT%5D+%28Enter+your+description+here%29).

### Describe the new feature

Is it possible to implement an installation package cache in UniGetUI, that is similar to auto-apt-proxy (AAP) in Linux?

AAP caches install packages so that when other devices on the LAN request to update an installed package, the information describing the package and the necessary binaries can be downloaded from a local device instead of downloading the package from across the Internet.

It would also be possible to have installations of UniGet-UI intercommunicate across the LAN, so when one PC gets an update it can then inform the other instances that an update is available allowing the other instances to then download the cached update.

### Describe how this new feature could help users

Implementing a feature similar to AAP will help to offload downloads from hosting services, reduce Internet usage (for people with a limited, bandwidth-restricted WAN) and potentially accelerate a PC rebuild.

**Comment by marticliment** [comment]
UniGetUI does not directly handle the download/install process, but rather interfaces with the package managers. Therefore, this cannot be implemented.
