### ISSUE TITLE
[IMPROVEMENT] Add Detection in Preparation of Property Name Changes Done in Latest PowershellGet

### ISSUE THREAD

**Issue by JAK1047** [marticliment/UniGetUI#2858]
### Please confirm these before moving forward.

- [X] I have searched for my feature proposal and have not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This improvement refers to an existing feature. If you want to suggest a new feature, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=new-feature&projects=&template=feature-request.yml&title=%5BFEATURE+REQUEST%5D+%28Enter+your+description+here%29).
- [X] This improvement is not a bug. If you want to report a bug, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=bug&projects=&template=bug-issue.yml&title=%5BBUG%5D+%28Enter+your+description+here%29).

### Describe the improvement

The new remake of PowershellGet that will start to be bundled with Powershell 7 installs changes a ton of things with module installation (saw it adds scoping to repositories which I'm sure will have side effects here). One of the smaller changes that will cause a break is a rename of the SourceLocation property to be an an actual Uri object:

Before
![image](https://github.com/user-attachments/assets/efbfe278-4f0a-4dea-abaf-a38505c0316f)

After
![image](https://github.com/user-attachments/assets/badaf40f-4015-41bf-ac09-418ee78d58d3)

This change breaks the Test-GalleryModuleUpdate
![image](https://github.com/user-attachments/assets/95ee6421-3b4d-42eb-9d04-60839a9350b8)

Simple fix would be to change:

`@(Get-PSRepository).ForEach({$URLs[$_.Name] = $_.SourceLocation})`

to

`@(Get-PSRepository).ForEach({$URLs[$_.Name] = If ($_.Uri) {$_.Uri.AbsoluteUri} Else {$_.SourceLocation}})`

### Describe how this improvement could help users

While currently the amount of folks on the prerelease are probably pretty low the GA release is right around the corner. May as well add checking for this ahead of time to cut off any issues when that drops.

**Comment by marticliment** [comment]
Migrating to the new command would work with old PowerShellGet, right?

**Comment by JAK1047** [comment]
Yeah works fine on current PowershellGet the only thing it adds is an If statement

![image](https://github.com/user-attachments/assets/e873ebcb-7c08-47aa-b6ba-09bba1437bd8)

All it's doing is checking if the Uri property exists on the object and using that as the hashtable value if so, and if not defaulting to SourceLocation like it does currently. There's probably more work that will need done for full compatibility when the new PowershellGet drops (will have to add commands to check both the CurrentUser and AllUsers scopes on the repos otherwise AllUsers is never checked) but I figured this was an easy win to cover most use cases ahead of time.

**Comment by marticliment** [comment]
Great! I will introduce the suggested changes then.
