### ISSUE TITLE
[BUG] New version update (3.1.2) got flagged as Trojan by Windows Defender (Trojan:Win32/Sabsik.TE.A!ml)

### ISSUE THREAD

**Issue by Dadangdut33** [marticliment/UniGetUI#2861]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.1.2

### Windows version, edition, and architecture

Windows 11 23H2 OS Build 22631.4317

### Describe your issue

While chilling using my PC i found that UnigetUI was trying to automatically update itself and it shows a brief command prompt. Usually it works just fine but for some reason this update now got flagged by Windows Defender as Trojan. I tried to reinstall the app by downloading the update directly from github but the same problem still shows up when trying to launch it (i know i could just exclude or ignore it but i thought i would submit this as an issue maybe there is a problem)

### Steps to reproduce the issue

1. Update the app or download new update
2. See problem happens

### UniGetUI Log

```text
-
```

### Package Managers Logs

```text
-
```

### Screenshots and videos

![image](https://github.com/user-attachments/assets/c2e6caf9-6c1c-4260-bd05-fda15659f427)
![image](https://github.com/user-attachments/assets/c210c226-e595-44b7-9cdb-6ceb9b0a4731)
![image](https://github.com/user-attachments/assets/ec222f00-1f3d-48da-93ef-69ddca3c8c72)
![image](https://github.com/user-attachments/assets/36b5adfa-fe43-4d13-b570-f2a7a4f54404)

**Comment by marticliment** [comment]
https://www.virustotal.com/gui/file/4f26ebead5c7de9c2c4186617abc9d05f5bb3676cb567223632427f20f54e448

**Comment by Dadangdut33** [comment]
alright thanks for the swift response 👍
