### ISSUE TITLE
[BUG] UniGetUI 3.1.1 doesnt start anymore

### ISSUE THREAD

**Issue by makedir** [marticliment/UniGetUI#2863]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.1.1

### Windows version, edition, and architecture

Windows 11 24h2

### Describe your issue

This is now the 3rd time this happens with different versions. Can you please try to stop breaking this program?

### Steps to reproduce the issue

-

### UniGetUI Log

```text
-
```

### Package Managers Logs

```text
-
```

**Comment by marticliment** [comment]
Any crash report on Event Viewer?

> Can you please try to stop breaking this program?
As you will understand, I don't intentionally break things...

**Comment by Yentis** [comment]
I have the same issue on 23H2
![image](https://github.com/user-attachments/assets/f542b7d4-fb22-49d9-92be-f78618db37d8)

**Comment by marticliment** [comment]
Disabling the internet makes UniGetUI work again?

**Comment by Yentis** [comment]
Yes, it starts if I disconnect my internet

**Comment by makedir** [comment]
I had this issue before on some earlier versions too some months ago. The resolution was to manually remove UnigetUI and reinstall the latest version. But that removed all the apps I had installed through chocolatey.

**Comment by makedir** [comment]
Beschreibung
Name der fehlerhaften Anwendung: UniGetUI.exe, Version: 3.1.1.0, Zeitstempel: 0x666b0000
Name des fehlerhaften Moduls: KERNELBASE.dll, Version: 10.0.19041.4957, Zeitstempel: 0xc5225d0f
Ausnahmecode: 0xc000027b
Fehleroffset: 0x0000000000133b32
ID des fehlerhaften Prozesses: 0x83c
Startzeit der fehlerhaften Anwendung: 0x01db24e56483d9d4
Pfad der fehlerhaften Anwendung: C:\Program Files\UniGetUI\UniGetUI.exe
Pfad des fehlerhaften Moduls: C:\WINDOWS\System32\KERNELBASE.dll
Berichtskennung: 32a21ffb-98ca-4efb-9ee6-44e68650e901
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:

**Comment by makedir** [comment]
It seems restarting UnigetUI a few times resolves this issue and you can update to 3.12

**Comment by pseisam** [comment]
> It seems restarting UnigetUI a few times resolves this issue and you can update to 3.12

This actually worked after a few restarts (<10). And they say doing the same over and over again and expecting other results is the definition of insane... :D

(So probably a race condition)

**Comment by makedir** [comment]
It happened now again here on 3.12. Crashing several times opening it. Until after 10 tries opening it or so, it opened. And I saw it announced an update to 3.13. I think this issue might be triggered, if there is an update push notification in the background, when the app launches.
