### ISSUE TITLE
[FEATURE REQUEST] Utilize elevation of UniGetUI for subcommands (aka Support stupid PolicyPak system)

### ISSUE THREAD

**Issue by cavanaug** [marticliment/UniGetUI#2868]
### Please confirm these before moving forward.

- [X] I have searched for my feature proposal and have not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This proposal is a completely new feature. If you want to suggest an improvement or an enhancement, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=enhancement&projects=&template=enhancement-improvement.yml&title=%5BENHANCEMENT%5D+%28Enter+your+description+here%29).

### Describe the new feature

I would like to support the policy pack application. Unfortunately this application does not support pseudo or G pseudo and requires special use of items that they build into the explorer. The only way to elevate is via a right click self elevate with PolicyPak. Normal elevation in windows or sudo simply do not work they fail. 

FWIW, I have researched the policy pack documentation and I've found no API or command line that allows for scripted automation in any way. I don't know how they sell this solution in such a crippled fashion but I hope eventually Microsoft makes more of Winget and other capabilities available to IT administrators so they stop using this stupid PolicyPak application.

Until then, my general workaround has been to run this self elevate with policy pack for a Powershell window and then run winget update --all. I however would much prefer to use Uniguet UI.

My suggested approach would be to allow the execution of UnigetUI elevated via this workaround. Perhaps add a dev setting in the app that allows for this elevation of the application to transitively pass elevation to all sub commands such as winget chocolatey or scoop. I know this is ugly but it's the only way I can see how to get this work in my environment.

Note, this is not a compromise of the policy pack system, even in my powershell example logs every system command that's run underneath it.   In this case it would just be logging all the commands that UnigetUI executes. So the data still exists it just supports a model that is far more convenient for common use cases.

### Describe how this new feature could help users

It will allow to support systems governed by PolicyPak system and/or systems where normal windows elevation or sudo do not work but still provide a mechanism to elevate an application such as UniGetUI

**Comment by marticliment** [comment]
I don't really understand how PolicyPack works.
So running `sudo` or similar is blocked? What can a process do to run elevated?

**Comment by cavanaug** [comment]
Yes so PolicyPak in combination with GPO effectively locks down your PC.   Via GPO they prevent folks from being in the Administrators group thus prevent standard elevation.  The only way to elevate is to do the "right click on exe, and select SelfElevate with PolicyPak"

So what I want to do is launch UniGetUI.exe via the right click workaround.   But then I need UniGetUI.exe to remain elevated, and then I believe launching any exe's would inherit this elevation without problem.

**Comment by cavanaug** [comment]
Ahh, that works...

**Comment by marticliment** [comment]
Should I close this issue then?

**Comment by cavanaug** [comment]
Ill close it.   The key thing here is that there is now a defined workaround that is discoverable via search.  :-)

Thanks...
