### ISSUE TITLE
[BUG] Random packages not able to update

### ISSUE THREAD

**Issue by makedir** [marticliment/UniGetUI#2889]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.1.2

### Windows version, edition, and architecture

Windows 11 24h2

### Describe your issue

It happens all the time, that random packages you installed through UniGetUI via WinGet source fail to update when an update comes out. This issue makes UniGetUI totally useless. The issue I have mostly on all my Pcs I have and the issue is also there since years.

There is no error in the package installation log it seems, yet it fails to update.

![image](https://github.com/user-attachments/assets/b956ab4b-75ca-4127-99e8-3ec8f413fefb)

This is just an example. I had issues like this in the past with all kinds of packages, ffmpeg for example, or random other packages. Also most Visual C++ update packages wont install/update via UniGetUI with an error.

### Steps to reproduce the issue

Example:

Just wanted to update yt-dlp to a new update UniGetUI shows, but it is unable to update. It was first installed through UniGetUI with WinGet source.

### UniGetUI Log

```text
-
```

### Package Managers Logs

```text
Starting package update operation for package id=yt-dlp.yt-dlp with Manager name=Winget
Given installation options are <InstallationOptions: SkipHashCheck=False;InteractiveInstallation=False;RunAsAdministrator=False;Version=;Architecture=;InstallationScope=;InstallationScope=;CustomParameters=;RemoveDataOnUninstall=False>
Process Executable     : C:\Users\maked\AppData\Local\Microsoft\WindowsApps\winget.exe
Process Call Arguments :  update --id "yt-dlp.yt-dlp" --exact --source winget --accept-source-agreements --disable-interactivity --silent --include-unknown --accept-package-agreements --force
Working Directory      : C:\Users\maked
Process Start Time     : Fr, 25.10.2024 03:15:50
-
Gefunden yt-dlp [yt-dlp.yt-dlp] Version 2024.10.22
Diese Anwendung wird von ihrem Besitzer an Sie lizenziert.
Microsoft ist nicht verantwortlich und erteilt keine Lizenzen für Pakete von Drittanbietern.
Dieses Paket erfordert folgende Abhängigkeiten:
- Pakete
Gyan.FFmpeg
(1/1) Gefunden FFmpeg [Gyan.FFmpeg] Version 7.1
Diese Anwendung wird von ihrem Besitzer an Sie lizenziert.
Microsoft ist nicht verantwortlich und erteilt keine Lizenzen für Pakete von Drittanbietern.
Download läuft https://github.com/GyanD/codexffmpeg/releases/download/7.1/ffmpeg-7.1-full_build.zip
-
\
|
/
-
\
|
¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦  1024 KB /  169 MB
¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦  11.0 MB /  169 MB
¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦  22.0 MB /  169 MB
¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦  33.0 MB /  169 MB
¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦  44.0 MB /  169 MB
¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦  55.0 MB /  169 MB
¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦  66.0 MB /  169 MB
¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦  76.0 MB /  169 MB
¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦  86.0 MB /  169 MB
¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦  96.0 MB /  169 MB
¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦   107 MB /  169 MB
¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦   119 MB /  169 MB
¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦   130 MB /  169 MB
¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦   141 MB /  169 MB
¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦   151 MB /  169 MB
¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦   163 MB /  169 MB
¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦   169 MB /  169 MB
Der Installer-Hash wurde erfolgreich überprüft
Archiv wird extrahiert...
Archiv erfolgreich extrahiert
Process Exit Code      : -1073741819
Process End Time       : Fr, 25.10.2024 03:16:17
```

**Comment by marticliment** [comment]
@makedir, running the upgrade command on a cmd window does work?
`winget update --id "yt-dlp.yt-dlp" --exact --source winget --accept-source-agreements --disable-interactivity --silent --include-unknown --accept-package-agreements --force`

**Comment by makedir** [comment]
Yes that command worked:

Microsoft Windows [Version 10.0.26100.2161]
(c) Microsoft Corporation. Alle Rechte vorbehalten.

C:\Users\maked>winget update --id "yt-dlp.yt-dlp" --exact --source winget --accept-source-agreements --disable-interactivity --silent --include-unknown --accept-package-agreements --force
Gefunden yt-dlp [yt-dlp.yt-dlp] Version 2024.10.22
Diese Anwendung wird von ihrem Besitzer an Sie lizenziert.
Microsoft ist nicht verantwortlich und erteilt keine Lizenzen für Pakete von Drittanbietern.
Dieses Paket erfordert folgende Abhängigkeiten:
  - Pakete
      Gyan.FFmpeg
(1/1) Gefunden FFmpeg [Gyan.FFmpeg] Version 7.1
Diese Anwendung wird von ihrem Besitzer an Sie lizenziert.
Microsoft ist nicht verantwortlich und erteilt keine Lizenzen für Pakete von Drittanbietern.
Der Installer-Hash wurde erfolgreich überprüft
Archiv wird extrahiert...
Archiv erfolgreich extrahiert

**Comment by marticliment** [comment]
Try to run the update command again on a command prompt, and when it finishes, run the following command 
```cmd
echo %errorlevel%
```
and post the output

**Comment by makedir** [comment]
```
C:\Users\maked>winget update --id "yt-dlp.yt-dlp" --exact --source winget --accept-source-agreements --disable-interactivity --silent --include-unknown --accept-package-agreements --force
Gefunden yt-dlp [yt-dlp.yt-dlp] Version 2024.10.22
Diese Anwendung wird von ihrem Besitzer an Sie lizenziert.
Microsoft ist nicht verantwortlich und erteilt keine Lizenzen für Pakete von Drittanbietern.
Dieses Paket erfordert folgende Abhängigkeiten:
  - Pakete
      Gyan.FFmpeg
(1/1) Gefunden FFmpeg [Gyan.FFmpeg] Version 7.1
Diese Anwendung wird von ihrem Besitzer an Sie lizenziert.
Microsoft ist nicht verantwortlich und erteilt keine Lizenzen für Pakete von Drittanbietern.
Der Installer-Hash wurde erfolgreich überprüft
Archiv wird extrahiert...
Archiv erfolgreich extrahiert

C:\Users\maked>echo %errorlevel%
-1073741819
```

**Comment by marticliment** [comment]
The update is still failing. The exit code, which in unsigned hexa is `0xC0000005` means that WinGet.exe has tried to access an invalid memory adress and has crashed, indicating that the issue here is caused by WinGet and not by UniGetUI.

I'd recommend to try resetting WinGet (you can do this from UniGetUI Settings -> WinGet -> Reset WinGet), and if the issue persists please post an issue on microsoft/winget-cli, as I can't fix this issue from UniGetUI

**Comment by makedir** [comment]
On that Pc there is this package installed

![image](https://github.com/user-attachments/assets/b28bf464-2572-4810-8506-eac92f3758a6)

where on my other Pc there is no Winget client, why?

**Comment by makedir** [comment]
resetting did not fix the issue.

**Comment by marticliment** [comment]
This is a PowerShell module for WinGet, used by UniGetUI to perform certain tasks. You shouldn't be worried about the Client. You can safely ignore it.

If resetting did not fix the issue, please open a new issue on microsoft/winget-cli. Your updates are failing because WinGet is crashing
