### ISSUE TITLE
[BUG] UnigetUI V3.1.2 - Code Signed Binaries not valid after 22-10-2024

### ISSUE THREAD

**Issue by SebCT** [marticliment/UniGetUI#2896]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.1.2

### Windows version, edition, and architecture

Windows 11 Pro 24H2 Build 26100.2161 x64

### Describe your issue

Hello!

Just saw that the code signed binaries from UniGetUI 3.1.2 are not valid anymore since 22-10-2024 (screenshot attached) - the signed binaries from 3.1.1 are still valid.

Not sure if it was a mistake with the new code signer certificate and will be corrected with the next release (hopefully)?

### UniGetUI Log

```text
Not necessary, the application still works
```

### Package Managers Logs

```text
Not necessary, the application still works
```

### Screenshots and videos

![image](https://github.com/user-attachments/assets/1a26b105-3466-49df-aa22-d125e10c5069)

**Comment by marticliment** [comment]
I will fix this. It looks like the files didn't get properly timestamped

**Comment by marticliment** [comment]
See UniGetUI 3.1.3
