### ISSUE TITLE
[IMPROVEMENT] Better UniGetUI autoupgrade experience

### ISSUE THREAD

**Issue by tomasz1986** [marticliment/UniGetUI#2905]
### Please confirm these before moving forward.

- [X] I have searched for my feature proposal and have not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This improvement refers to an existing feature. If you want to suggest a new feature, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=new-feature&projects=&template=feature-request.yml&title=%5BFEATURE+REQUEST%5D+%28Enter+your+description+here%29).
- [X] This improvement is not a bug. If you want to report a bug, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=bug&projects=&template=bug-issue.yml&title=%5BBUG%5D+%28Enter+your+description+here%29).

### Describe the improvement

Currently, the process looks like this:

1. Suddenly, a random CMD window pops up, then closes after a few seconds.
2. Next, an upgrade prompt pops up from UniGetUI.
3. The user is forced to decide whether to install the new version or not.
4. The new version installs.

The problem is that all this may happen at a random moment. For instance, just today I had the pop-ups show when I was in the middle of conducting a university class, which is not acceptable. As there is no way to control automatic upgrades, I'm basically forced to disable them.

I think the best way to prevent such issues would be to implement a fully silent automatic upgrade mechanism. Alternatively, automatic upgrades could occur only at a specific moment, e.g. on system start, and not in the middle of work.

### Describe how this improvement could help users

Silent or predictable (e.g. on boot) upgrades would prevent pop-ups from showing randomly in the middle of important work, while delivering a presentation, etc.

**Comment by marticliment** [comment]
Yes, I think this makes sense. I will see what I can do

**Comment by tomasz1986** [comment]
Thank you very much for a lightning fast reaction! I will be looking forward to testing any further improvements in this area.

Another situation, where I've experienced issues with the current mechanism, is with UniGetUI installed on a family member's computer. As they are not exactly tech-savvy, they've got no idea what the pop-ups are for and are basically scared by them.
