### ISSUE TITLE
[IMPROVEMENT] Support PowerShell modules installed via PSResourceGet

### ISSUE THREAD

**Issue by dsolodow** [marticliment/UniGetUI#2940]
### Please confirm these before moving forward.

- [X] I have searched for my feature proposal and have not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This improvement refers to an existing feature. If you want to suggest a new feature, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=new-feature&projects=&template=feature-request.yml&title=%5BFEATURE+REQUEST%5D+%28Enter+your+description+here%29).
- [X] This improvement is not a bug. If you want to report a bug, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=bug&projects=&template=bug-issue.yml&title=%5BBUG%5D+%28Enter+your+description+here%29).

### Describe the improvement

Have noticed that the option to update PowerShell modules uses/depends on Update-Module
It doesn't detect modules installed by Microsoft.PowerShell.PSResourceGet so they get left behind

### Describe how this improvement could help users

Keep PowerShell modules updated when installed by either Microsoft supported module manager.

**Comment by marticliment** [comment]
Fixed on https://github.com/marticliment/UniGetUI/commit/7ea97506afac3784aecc90c25c4516d77f8ce8ab
