### ISSUE TITLE
[IMPROVEMENT] Add an option to delete desktop shortcut after update/install

### ISSUE THREAD

**Issue by MrMAXVW** [marticliment/UniGetUI#2942]
### Please confirm these before moving forward.

- [X] I have searched for my feature proposal and have not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This improvement refers to an existing feature. If you want to suggest a new feature, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=new-feature&projects=&template=feature-request.yml&title=%5BFEATURE+REQUEST%5D+%28Enter+your+description+here%29).
- [X] This improvement is not a bug. If you want to report a bug, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=bug&projects=&template=bug-issue.yml&title=%5BBUG%5D+%28Enter+your+description+here%29).

### Describe the improvement

I was using patchmypc all day long before and discover unigetui recently
this is a pretty good software! but one feature I would like to see is adding an option for user to enable 'auto delete shortcut on desktop after installation'
this is pretty useful for some dudes who have OCD lol

### Describe how this improvement could help users

for clean desktop users, they dont need to manually delete the shortcut on desktop
and it should be a pretty easy function to add I guess? thanks a lot

**Comment by mrixner** [comment]
I don't think there's a way to find desktop shortcuts automatically, but my suggestion for this would be to have a file selector in the package details page that allows you to select ANY file - presumably re-added by the package on installation / update - like the desktop `.lnk` file, that UniGetUI would then delete after an update process. Then, it doesn't require any changes to the package managers and still achieves the intended purpose.

**Comment by marticliment** [comment]
There could be some pre and post update scan to detect changed .lnk files

**Comment by MrMAXVW** [comment]
![image](https://github.com/user-attachments/assets/b63b2c8c-947b-46d2-a17d-f19595c685a6)
Thanks all, here's a printscreen of Patchmypc. I am not sure how they delete the shortcut but it works pretty well.
I think they did scan the desktop for lnk

**Comment by mrixner** [comment]
That's a good idea, however in the case of an unrelated `.lnk` file being added coincidentally to the desktop during installation, for perhaps concurrent installations, I feel there should be a confirmation request the first time it tries to delete a shortcut. Otherwise (because I can't do UI) I would do this right now; this has bothered me for a little while.

Here's what I would recommend - a pre update / post update scan, and if new link files are on and Delete Desktops setting is on, show the user a dialog showing the new link files and ask them to choose which ones to automatically delete in the future.

**Comment by Merlin8000** [comment]
I loaded up the issues page to ask for exactly this.

**Comment by marticliment** [comment]
> That's a good idea, however in the case of an unrelated `.lnk` file being added coincidentally to the desktop during installation, for perhaps concurrent installations, I feel there should be a confirmation request the first time it tries to delete a shortcut. Otherwise (because I can't do UI) I would do this right now; this has bothered me for a little while.

That would be an opt-in feature

**Comment by mrixner** [comment]
> That would be an opt-in feature

> Delete Desktops setting is on

Of course it would. Mucking with someone's desktop if they didn't ask you to is a terrible idea.
