### ISSUE TITLE
[BUG] (Enter your description here) 卸载jdk22后，不能卸载,只能用控制面板卸载

### ISSUE THREAD

**Issue by whq888** [marticliment/UniGetUI#2943]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.1.3

### Windows version, edition, and architecture

win11

### Describe your issue

卸载jdk22后，不能卸载,只能用控制面板卸载

### Steps to reproduce the issue

卸载jdk22后，不能卸载,只能用控制面板卸载

### UniGetUI Log

```text
卸载jdk22后，不能卸载,只能用控制面板卸载
```

### Package Managers Logs

```text
卸载jdk22后，不能卸载,只能用控制面板卸载
```

### Relevant information

卸载jdk22后，不能卸载,只能用控制面板卸载

### Screenshots and videos

卸载jdk22后，不能卸载,只能用控制面板卸载

**Comment by marticliment** [comment]
If this issue is only with jdk22, please report this issue to the package manager you are using to uninstall this package
