### ISSUE TITLE
[IMPROVEMENT] Limit parallel task queue run

### ISSUE THREAD

**Issue by CrazyJannis44** [marticliment/UniGetUI#2951]
### Please confirm these before moving forward.

- [X] I have searched for my feature proposal and have not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This improvement refers to an existing feature. If you want to suggest a new feature, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=new-feature&projects=&template=feature-request.yml&title=%5BFEATURE+REQUEST%5D+%28Enter+your+description+here%29).
- [X] This improvement is not a bug. If you want to report a bug, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=bug&projects=&template=bug-issue.yml&title=%5BBUG%5D+%28Enter+your+description+here%29).

### Describe the improvement

Set a custom limit by amount or by cpu and ram usage how many tasks can be run parallel. Also it would be cool to limit the download speed so you can keep your system always up to date even while gaming uwu#
Another cool thing would be an easy setting to locate all installations of all installer tools in sub directories of a specific directory set by the user

### Describe how this improvement could help users

Making always keeping everything up to date more attractive

**Comment by marticliment** [comment]
The tasks could be limited to a number, but CPU and/or RAM usage is not really possible due to the fact that UniGetUI does not directly handle the process of installing and updating packages
