### ISSUE TITLE
Fehler beim Update des Microsoft.WinGet.Client

### ISSUE THREAD

**Issue by Paul051962** [marticliment/UniGetUI#2964]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.1.3

### Windows version, edition, and architecture

Windows 11 23H2 Build (22631.4391)

### Describe your issue

Ich habe versucht, auch als Admin, den Microsoft.WinGet.Client zu installieren, aber der Vorgang wurde immer abgebrochen.

Das ist die Datei welche verwendet werden soll.
https://marticliment.com/unigetui/share?name=Microsoft.WinGet.Client&id=Microsoft.WinGet.Client&sourceName=PSGallery&managerName=PowerShell+5.x 

Es wäre sehr hilfreich, wenn mir jemand helfen könnte.

### Steps to reproduce the issue

Ich habe versucht, auch als Admin, den Microsoft.WinGet.Client zu installieren, aber der Vorgang wurde immer abgebrochen. Ich kann nicht verstehen warum.
Sollten Sie Fragen haben oder zusätzliche Informationen benötigen, dann sagen sie es mir.

Mfg
Paul

### UniGetUI Log

```text
https://marticliment.com/unigetui/share?name=Microsoft.WinGet.Client&id=Microsoft.WinGet.Client&sourceName=PSGallery&managerName=PowerShell+5.x
```

### Package Managers Logs

```text
Update-Module : Es wurde kein Parameter gefunden, der dem Parameternamen "Scope" entspricht.
In Zeile:1 Zeichen:68
+ ... e -Name Microsoft.WinGet.Client -Confirm:$false -Force -Scope Current ...
+                                                            ~~~~~~
+ CategoryInfo          : InvalidArgument: (:) [Update-Module], ParameterBindingException
+ FullyQualifiedErrorId : NamedParameterNotFound,Update-Module
```

**Comment by Paul051962** [comment]
Ich hatte den Fehler aus Versehen geschlossen.

**Comment by marticliment** [comment]
Duplicate of https://github.com/marticliment/UniGetUI/issues/2814
