### ISSUE TITLE
[IMPROVEMENT] (Foolish LOG Live chars during Package installation)

### ISSUE THREAD

**Issue by pulsar14** [marticliment/UniGetUI#2986]
### Please confirm these before moving forward.

- [X] I have searched for my feature proposal and have not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This improvement refers to an existing feature. If you want to suggest a new feature, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=new-feature&projects=&template=feature-request.yml&title=%5BFEATURE+REQUEST%5D+%28Enter+your+description+here%29).
- [X] This improvement is not a bug. If you want to report a bug, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=bug&projects=&template=bug-issue.yml&title=%5BBUG%5D+%28Enter+your+description+here%29).

### Describe the improvement

How absurd is this output?

```
██████████████████████████████  85.2 MB / 85.2 MB
██████████████████████████████  85.2 MB / 85.2 MB
Verifica dell'hash di installazione completata
Avvio installazione pacchetto in corso...
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
/
-
\
|
Installazione riuscita
```

_By removing these messy chars during the installation, the LOG become more clear and readable_

```
-
\
|
/
-
\
|
/ 
```

### Describe how this improvement could help users

```
██████████████████████████████  85.2 MB / 85.2 MB
██████████████████████████████  85.2 MB / 85.2 MB
Verifica dell'hash di installazione completata
**TIMESTAMP**: Avvio installazione pacchetto in corso...

**TIMESTAMP**: Installazione riuscita

> More clear, more readable!
> Don't You agree?

**Comment by marticliment** [comment]
This issue was fixed on e7fef595bbdc0d3b08783d62ad7034002e898caa.
Next version will have the issue fixed
