### ISSUE TITLE
[IMPROVEMENT] Disable self-updater by default on Microsoft Store release

### ISSUE THREAD

**Issue by assyrus-favolo** [marticliment/UniGetUI#2991]
### Please confirm these before moving forward.

- [X] I have searched for my feature proposal and have not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This improvement refers to an existing feature. If you want to suggest a new feature, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=new-feature&projects=&template=feature-request.yml&title=%5BFEATURE+REQUEST%5D+%28Enter+your+description+here%29).
- [X] This improvement is not a bug. If you want to report a bug, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=bug&projects=&template=bug-issue.yml&title=%5BBUG%5D+%28Enter+your+description+here%29).

### Describe the improvement

I'd rather rely on the Microsoft Store to update apps coming from there, without the app breaking out of the system set in place.

### Describe how this improvement could help users

For example, as soon as I installed the latest version on there today, I got an automatic update from within the app and it just told me that it would install after I restarted the app, so I didn't even have the chance to configure the app beforehand to disable this behavior. I feel like this is just unexpected and should be opted into instead of out

**Comment by marticliment** [comment]
The microsoft store release does not get updated via microsoft store, since Win32 mirosoft store apps must update themselves.

**Comment by assyrus-favolo** [comment]
Oh, sorry didn't know that, thanks for clarifying!
