### ISSUE TITLE
[BUG]Unable to install updates for Microsoft.WinGet.Client

### ISSUE THREAD

**Issue by d3721s** [marticliment/UniGetUI#3004]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.1.3

### Windows version, edition, and architecture

win10

### Describe your issue

![image](https://github.com/user-attachments/assets/aed01270-5be1-4159-b331-aea5ac0ea98f)
![image](https://github.com/user-attachments/assets/ebe87826-dd16-49b3-97e2-5aae7a0efd78)

### UniGetUI Log

```text
[2024/11/22 0:14:41] Loaded operation parameters for package id=Microsoft.WinGet.Client on manager PowerShell and operation Update: Update-Module -Name Microsoft.WinGet.Client -Confirm:$false -Force  -Scope CurrentUser
```

### Package Managers Logs

```text
Starting package update operation for package id=Microsoft.WinGet.Client with Manager name=PowerShell
Given installation options are <InstallationOptions: SkipHashCheck=True;InteractiveInstallation=False;RunAsAdministrator=True;Version=;Architecture=;InstallationScope=;InstallationScope=;CustomParameters=;RemoveDataOnUninstall=False>
Process Executable     : C:\Program Files\UniGetUI\Assets\Utilities\gsudo.exe
Process Call Arguments : "C:\Windows\system32\windowspowershell\v1.0\powershell.exe"  -NoProfile -Command Update-Module -Name Microsoft.WinGet.Client -Confirm:$false -Force  -Scope CurrentUser
Working Directory      : C:\Users\runyu
Process Start Time     : 2024/11/22 0:10:05
Update-Module : �Ҳ�����������ơ�Scope��ƥ��Ĳ�����
����λ�� ��:1 �ַ�: 68
+ ... e -Name Microsoft.WinGet.Client -Confirm:$false -Force -Scope Current ...
+                                                            ~~~~~~
+ CategoryInfo          : InvalidArgument: (:) [Update-Module]��ParameterBindingException
+ FullyQualifiedErrorId : NamedParameterNotFound,Update-Module
Process Exit Code      : 1
Process End Time       : 2024/11/22 0:10:06
```

**Comment by marticliment** [comment]
Please test the latest beta release: https://github.com/marticliment/UniGetUI/releases/tag/3.1.4-beta1

**Comment by d3721s** [comment]
> Please test the latest beta release: https://github.com/marticliment/UniGetUI/releases/tag/3.1.4-beta1

![image](https://github.com/user-attachments/assets/5b9462c2-cb76-40ca-be85-7b2a7a18e700)
exactly the same as before
![image](https://github.com/user-attachments/assets/3d068857-52cb-4093-b2d7-a681796e18ad)
