### ISSUE TITLE
[IMPROVEMENT] remove repeating  -\|/-\|/ characters from Live Output 

### ISSUE THREAD

**Issue by MovGP0** [marticliment/UniGetUI#3006]
### Please confirm these before moving forward.

- [X] I have searched for my feature proposal and have not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This improvement refers to an existing feature. If you want to suggest a new feature, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=new-feature&projects=&template=feature-request.yml&title=%5BFEATURE+REQUEST%5D+%28Enter+your+description+here%29).
- [X] This improvement is not a bug. If you want to report a bug, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=bug&projects=&template=bug-issue.yml&title=%5BBUG%5D+%28Enter+your+description+here%29).

### Describe the improvement

Installation of some packages produce the following string of characters in repeating sequences:
```
\
|
/
-
\
|
/
-
```

This output repeats and can become very long when installing large applications, which prevents users from looking up the relevant information before this sequence. 

Either:
- Omit repeating sequences of those characters from the "Live output" window.
- Handle the carriage return without newline (`\r`) character to not create a new line, but move the cursor to the first character of the line, such that the last output line gets overriden

### Describe how this improvement could help users

Users should get relevant information when inspecting the *Live output*, without endlessly clutter

**Comment by marticliment** [comment]
This issue should be fixed on the latest prerelease build
