### ISSUE TITLE
[FEATURE REQUEST] Option to install scoop directly through the Uniget Installer

### ISSUE THREAD

**Issue by Heus-Sueh** [marticliment/UniGetUI#3012]
### Please confirm these before moving forward.

- [X] I have searched for my feature proposal and have not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This proposal is a completely new feature. If you want to suggest an improvement or an enhancement, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=enhancement&projects=&template=enhancement-improvement.yml&title=%5BENHANCEMENT%5D+%28Enter+your+description+here%29).

### Describe the new feature

Option to install scoop directly through the Uniget Installer, similar to what is already offered for chocolatey, with a simple checkbox.

![image](https://github.com/user-attachments/assets/4639d7f7-a14b-407f-adb0-e853c5b89522)

### Describe how this new feature could help users

Access to a large repository of apps easily without having to install it manually via powershell

**Comment by marticliment** [comment]
I don't understand what you mean

**Comment by Heus-Sueh** [comment]
> I don't understand what you mean

sorry, I should have put the title as "uniget installer" to make it clearer

have another checkbox below `install chocolatey` to install scoop:
![image](https://github.com/user-attachments/assets/57c03955-04c4-406e-bb8a-84615f64a4a8)

**Comment by marticliment** [comment]
This is not possible due to the way in which Scoop is installed on the system.
Chocolatey is bundled with UniGetUI, and does not actually get installed.
Scoop, instead, requires a system install, and wouldn't be a good practice to run the script from the installer.
