### ISSUE TITLE
[IMPROVEMENT] (Enter your description here)

### ISSUE THREAD

**Issue by swRains** [marticliment/UniGetUI#3030]
### Please confirm these before moving forward.

- [X] I have searched for my feature proposal and have not found a work-in-progress/duplicate/resolved/discarded issue.
- [ ] This improvement refers to an existing feature. If you want to suggest a new feature, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=new-feature&projects=&template=feature-request.yml&title=%5BFEATURE+REQUEST%5D+%28Enter+your+description+here%29).
- [X] This improvement is not a bug. If you want to report a bug, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=bug&projects=&template=bug-issue.yml&title=%5BBUG%5D+%28Enter+your+description+here%29).

### Describe the improvement

When I was checking the installation log of a certain program, I found a large number of dynamically rotating slashes, which made it difficult for me to locate the cause of the installation failure. It is recommended that the program installation log should not display dynamically rotating slashes, which will make it easier to check the cause of the installation failure or whether the installation is proceeding normally.

我在查看某个程序安装日志时发现有大量的动态旋转的斜线，这让我无法定位安装失败的原因，建议程序安装日志不要显示动态旋转的斜线，这一能够更方便地查询安装失败的原因或者安装是否在正常进行。

### Describe how this improvement could help users

It is convenient for administrators to locate whether the fault is caused by permissions, network or other reasons.

方便管理员定位故障到底是权限、网络还是其他原因。

**Comment by marticliment** [comment]
This issue has already been fixed on the latest beta release
