### ISSUE TITLE
[IMPROVEMENT] Make "Live output" scrollable, prevent spam output

### ISSUE THREAD

**Issue by emmi-ari** [marticliment/UniGetUI#3037]
### Please confirm these before moving forward.

- [X] I have searched for my feature proposal and have not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This improvement refers to an existing feature. If you want to suggest a new feature, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=new-feature&projects=&template=feature-request.yml&title=%5BFEATURE+REQUEST%5D+%28Enter+your+description+here%29).
- [X] This improvement is not a bug. If you want to report a bug, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=bug&projects=&template=bug-issue.yml&title=%5BBUG%5D+%28Enter+your+description+here%29).

### Describe the improvement

Currently the live output window is unscrollable due to the loading animation that generates one new line per "animation" step, which makes it impossible to scroll up to the beginning of the output, because as soon as there's a new line it scrolls to the bottom.
![Screencapture](https://github.com/user-attachments/assets/19e75d34-f604-495c-9e95-736d7e333f97)

My suggestions are:
* Make the loading "animation" static, so that it doesn't generate new lines indefinitely for the duration of the loading process.
* Don't force the user to jump to the bottom of the output just because a new line has appeared.

### Describe how this improvement could help users

So that the live output is actually usable to read installation details for a package when a user wants to, even when there's something loading.

**Comment by marticliment** [comment]
The "spam" output was fixed on the latest beta release. The scrollable live output gets fixed with the previous fix
