### ISSUE TITLE
[FEATURE REQUEST] Bandwith control for download

### ISSUE THREAD

**Issue by drummbelbummel** [marticliment/UniGetUI#3045]
### Please confirm these before moving forward.

- [X] I have searched for my feature proposal and have not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This proposal is a completely new feature. If you want to suggest an improvement or an enhancement, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=enhancement&projects=&template=enhancement-improvement.yml&title=%5BENHANCEMENT%5D+%28Enter+your+description+here%29).

### Describe the new feature

I want to suggest an option to control the maximum bandwith for a download. Unfortunately not all people do have fast internet. Having the option to limit the bandwith would be great as it could better run in the background.

### Describe how this new feature could help users

users with limited bandwith

**Comment by marticliment** [comment]
This is not possible, UniGetUI does not directly handle the download process.
