### ISSUE TITLE
Additional software updates

### ISSUE THREAD

**Issue by MurraySobol** [marticliment/UniGetUI#3062]
### Please confirm these before moving forward.

- [X] I have searched for my feature proposal and have not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This proposal is a completely new feature. If you want to suggest an improvement or an enhancement, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=enhancement&projects=&template=enhancement-improvement.yml&title=%5BENHANCEMENT%5D+%28Enter+your+description+here%29).

### Describe the new feature

Using another product (Norton 360) I found another update available:
![image](https://github.com/user-attachments/assets/d5137a5b-595e-466d-808e-63b90c00e397)
Would i be possible / feasible to integrate this type of update into UniGetUi??

### Describe how this new feature could help users

Additional software updates  would be available for the user to upgrade, all in one place.

**Comment by marticliment** [comment]
This update would have come through WinGet, but it may have taken a day or two
