### ISSUE TITLE
[BUG] UI: "Manage ignored updates" list is blank - Adding new ignores, list remains empty

### ISSUE THREAD

**Issue by redactedscribe** [marticliment/UniGetUI#3065]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.1.4-beta 2

### Windows version, edition, and architecture

Windows 11 Pro

### Describe your issue

See title. Blank ignored updates list. After adding 2 more ignores, the list is still blank / empty. Not sure if the list looked empty on stable. Definitely broken in beta 2.

### UniGetUI Log

```text
-
```

### Package Managers Logs

```text
-
```

### Screenshots and videos

![UniGetUI_2024-12-12_13-21-29](https://github.com/user-attachments/assets/2a8dffdc-fb89-4f43-99d7-a6be2bba6796)

**Comment by marticliment** [comment]
Please share UniGetUI logs
