### ISSUE TITLE
[BUG] Software updates (package indexes) are checked for on startup when setting disabled

### ISSUE THREAD

**Issue by redactedscribe** [marticliment/UniGetUI#3066]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.1.4 beta 2

### Windows version, edition, and architecture

Windows 11 Pro

### Describe your issue

Every time I launch UniGetUI, software updates are checked for (I presume this is what "Update package indexes on launch" means and does). I have the option *disabled*. I want to launch UniGetUI without checks for package updates occurring.

The "Update preferences" settings are all disabled too.

### UniGetUI Log

```text
-
```

### Package Managers Logs

```text
-
```

### Screenshots and videos

![UniGetUI_2024-12-12_13-33-27](https://github.com/user-attachments/assets/7c7a2e68-8c5d-43b7-b06e-f504e48105c5)

![UniGetUI_2024-12-12_13-37-18](https://github.com/user-attachments/assets/61774df6-78a0-4f39-b4e3-919f5c5db102)

**Comment by marticliment** [comment]
> Every time I launch UniGetUI, software updates are checked for (I presume this is what "Update package indexes on launch" means and does). I have the option _disabled_. I want to launch UniGetUI without checks for package updates occurring.

Nope, this is not true.

Update package indexes on launch triggers the package managers that support such behaviour to reload all the new package lists and catalogs from the internet. This has nothing to do with updates being checked or not. (Of course, updating the indexes may help listing more recent updates, that would otherwhise take a bit longer to appear)

**Comment by marticliment** [comment]
UniGetUI will always check for updates on launch. Disabling the "Check for updates periodically" prevents UniGetUI from checking updates **again** after X time

**Comment by marticliment** [comment]
What you are arguing makes sense, I will check the exact implications of this code and reply here, as I can't remember them right now. I remember it made sense to have such option, I can't remember exactly why.

**Comment by marticliment** [comment]
It happens that 2 months ago i changed how package index refreshing is handled (current UniGetUI versions will trigger the refresh before checking for updates, only if the refresh wasn't triggered in the last 10 minutes). However, apparently I forgot to remove this outdated setting string, as it does nothing since said change was introduced. (Before, UniGetUI would only update the indexes on launch, only if said setting was enabled)
