### ISSUE TITLE
[BUG] Update of Martchus.syncthingtray winget package fail (Uninstallation program failed with exit code: 0x8a150003)

### ISSUE THREAD

**Issue by LbqpdL** [marticliment/UniGetUI#3069]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.1.3

### Windows version, edition, and architecture

Windows 11 Pro 23H2 1000.22700.1055.0

### Describe your issue

Hello,
I installed syncthingtray from winget repository, through the uniget-UI interface:
![395256206-8c8a7db9-b456-486f-a239-5b9b5783a5f0](https://github.com/user-attachments/assets/79ca77da-fdf7-41d8-aa6f-93be267565aa)

Today the update failed with the following error:

> Starting package update operation for package id=Martchus.syncthingtray with Manager name=Winget
> Given installation options are <InstallationOptions: SkipHashCheck=False;InteractiveInstallation=False;RunAsAdministrator=False;Version=;Architecture=;InstallationScope=;InstallationScope=;CustomParameters=;RemoveDataOnUninstall=False>
> Process Executable     : C:\Users\JulienCoubronne\AppData\Local\Microsoft\WindowsApps\winget.exe
> Process Call Arguments :  update --id "Martchus.syncthingtray" --exact --source winget --accept-source-agreements --disable-interactivity --silent  --include-unknown --accept-package-agreements --force
> Working Directory      : C:\Users\JulienCoubronne
> Process Start Time     : 13/12/2024 12:24:44
>
>
> Trouvé Syncthing Tray [Martchus.syncthingtray] Version 1.6.4
> La licence d’utilisation de cette application vous est octroyée par son propriétaire.
> Microsoft n’est pas responsable des paquets tiers et n’accorde pas de licences à ceux-ci.
> Le code de hachage de l’installation a été vérifié avec succès
> Extraction des archives...
> Extraction de l’archive réussie
> Début de la désinstallation du paquet...
> Une erreur inattendue s'est produite lors de l'exécution de la commande :
> remove: Acc�s refus�.: "C:\Users\JulienCoubronne\AppData\Local\Microsoft\WinGet\Packages\Martchus.syncthingtray_Microsoft.Winget.Source_8wekyb3d8bbwe\syncthingtray-1.6.3-x86_64-w64-mingw32.exe"
> Échec du programme de désinstallation avec le code de sortie : 0x8a150003 : Échec de l’exécution de la commande

Note : I was not asked for admin privileges

OS: Windows 11 Pro

Syncthing installed alongside with syncthingtray
![395256941-8f76ed05-0c8f-4563-8c3f-5a4eaabe3735](https://github.com/user-attachments/assets/c10cd2f5-5d59-4767-8f79-e920a2945687)

### UniGetUI Log

```text
[13/12/2024 12:24:44] Loaded operation parameters for package id=Martchus.syncthingtray on manager Winget and operation Update: update --id "Martchus.syncthingtray" --exact --source winget --accept-source-agreements --disable-interactivity --silent  --include-unknown --accept-package-agreements --force
```

### Package Managers Logs

```text
——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListInstalledPackages
Process start time: 13/12/2024 12:24:40
Process end time:   13/12/2024 12:24:43

-- Task information
 ...

The task reported success

——————————————————————————————————————————
```

**Comment by marticliment** [comment]
what happens if you upgrade from the command-line?

**Comment by marticliment** [comment]
I am afraid that, since this issue can also be caused by winget.exe, the cause is not UniGetUI, but rather WinGet. You may want to contact the package publisher (in this case `Martchus`) to let them know that their package can not be installed/upgraded properly

**Comment by LbqpdL** [comment]
I already opened a support ticket from the dev: https://github.com/Martchus/syncthingtray/issues/303

**Comment by Martchus** [comment]
I am not the publisher of that winget package.

**Comment by marticliment** [comment]
Then an issue should be opened on `microsoft/winget-pkgs`

**Comment by LbqpdL** [comment]
OK, thank you for the support, I will seek the best issue tracker to raise this issue.
Best regards,

**Comment by LbqpdL** [comment]
Hello, I was able to circumvent the issue by killing the running process before applying the update.

Steps:

- Quit the running process (kill the process through Windows Manager, or if you have enabled the system tray icon during the first install, quit the process from there)
- Launch the update from Uniget-UI

**Comment by marticliment** [comment]
Perhaps the installer is not attempting to close the app if it is running...
