### ISSUE TITLE
[IMPROVEMENT] Automatically (prompt to) reinvoke (un)installers interactively when files they require are in use.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [marticliment/UniGetUI#3095]
### Please confirm these before moving forward.

- [X] I have searched for my feature proposal and have not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This improvement refers to an existing feature. If you want to suggest a new feature, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=new-feature&projects=&template=feature-request.yml&title=%5BFEATURE+REQUEST%5D+%28Enter+your+description+here%29).
- [X] This improvement is not a bug. If you want to report a bug, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=bug&projects=&template=bug-issue.yml&title=%5BBUG%5D+%28Enter+your+description+here%29).

### Describe the improvement

Reinvoking `winget upgrade 'OBSProject.OBSStudio'` with the `-i` flag [^2] allows the user to actionably close the applications that are utilizing the files, [^1] which OBS necessitates access to, in order to upgrade itself.

[^1]: https://obsproject.com/forum/threads/please-close-this-these-application-before-installing-obs-fix.125012/post-667767
[^2]: https://github.com/microsoft/winget-pkgs/issues/105965#issuecomment-2460765408

### Describe how this improvement could help users

Currently, a user must read the failure log, ascertain which error message is relevant, understand it, and locate how to reinvoke the upgrader interactively. This is infeasible to expect of the userbase of UniGetUI.

**Comment by marticliment** [comment]
> Reinvoking `winget upgrade 'OBSProject.OBSStudio'` with the `-i` flag [1](#user-content-fn-2-7c5488daa10807a5d6a0b017254508f0) allows the user to actionably close the applications that are utilizing the files, [2](#user-content-fn-1-7c5488daa10807a5d6a0b017254508f0) which OBS necessitates access to, in order to upgrade itself.

This is not exactly true.
Using the `-i` flag triggers the installer to show in a graphical mode (not automated), and it happens to be the case that the installer/uninstaller for OBS does only handle the case where it is already running when run interactively. It would not make sense to trigger the `interactive` install mode when an operation fails due to a running application, since each installer will handle this in a different way (and OBS installer should already take care of the running app when running interactively)

**Comment by RokeJulianLockhart** [comment]
> It would not make sense to trigger the interactive install mode when an operation fails due to a running application, since each installer will handle this in a different way

@marticliment, I suppose it would be infeasible to maintain a whitelist.

> OBS installer should already take care of the running app when running interactively

In my case, the running application was part of my driver software, so it can't.

**Comment by marticliment** [comment]
The thing here is that OBS is the only installer who exposes this behaviour.

What you can do is set OBS installation options to update interactively
