### ISSUE TITLE
[BUG] "Version to Install" Not Showing

### ISSUE THREAD

**Issue by mrixner** [marticliment/UniGetUI#3096]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.1.4

### Windows version, edition, and architecture

Windows 11 Home

### Describe your issue

Even though UniGetUI seems to be detecting past versions of a package, it's not putting them in the dropdown and allowing me to change the version to install.

### Steps to reproduce the issue

1) Right-click any package
2) Observe the unusable "version to install" dropdown

### UniGetUI Log

```text
[12/19/2024 4:43:40 PM] Found 218 versions for package Id=google-api-python-client on manager Pip
```

### Package Managers Logs

```text
Logged subprocess-based task on manager Pip. Task type is LoadPackageVersions
Subprocess executable: "C:\Users\<username>\AppData\Local\Programs\Python\Python312\python.exe"
Command-line arguments: " -m pip index versions google-api-python-client"
Process start time: 12/19/2024 4:43:38 PM
Process end time:   12/19/2024 4:43:40 PM

-- Process STDOUT
  google-api-python-client (2.156.0)
  Available versions: 2.156.0, 2.155.0, 2.154.0, 2.153.0, 2.152.0, 2.151.0, 2.150.0, 2.149.0, 2.148.0, 2.147.0, 2.146.0, 2.145.0, 2.144.0, 2.143.0, 2.142.0, 2.141.0, 2.140.0, 2.139.0, 2.138.0, 2.137.0, 2.136.0, 2.135.0, 2.134.0, 2.133.0, 2.132.0, 2.131.0, 2.130.0, 2.129.0, 2.128.0, 2.127.0, 2.126.0, 2.125.0, 2.124.0, 2.123.0, 2.122.0, 2.121.0, 2.120.0, 2.119.0, 2.118.0, 2.117.0, 2.116.0, 2.115.0, 2.114.0, 2.113.0, 2.112.0, 2.111.0, 2.110.0, 2.109.0, 2.108.0, 2.107.0, 2.106.0, 2.105.0, 2.104.0, 2.103.0, 2.102.0, 2.101.0, 2.100.0, 2.99.0, 2.98.0, 2.97.0, 2.96.0, 2.95.0, 2.94.0, 2.93.0, 2.92.0, 2.91.0, 2.90.0, 2.89.0, 2.88.0, 2.87.0, 2.86.0, 2.85.0, 2.84.0, 2.83.0, 2.82.0, 2.81.0, 2.80.0, 2.79.0, 2.78.0, 2.77.0, 2.76.0, 2.75.0, 2.74.0, 2.73.0, 2.72.0, 2.71.0, 2.70.0, 2.69.0, 2.68.0, 2.66.0, 2.65.0, 2.64.0, 2.63.0, 2.62.0, 2.61.0, 2.60.0, 2.59.0, 2.58.0, 2.57.0, 2.56.0, 2.55.0, 2.54.0, 2.53.0, 2.52.0, 2.51.0, 2.50.0, 2.49.0, 2.48.0, 2.47.0, 2.46.0, 2.45.0, 2.44.0, 2.43.0, 2.42.0, 2.41.0, 2.40.0, 2.39.0, 2.38.0, 2.37.0, 2.36.0, 2.35.0, 2.34.0, 2.33.0, 2.32.0, 2.31.0, 2.30.0, 2.29.0, 2.28.0, 2.27.0, 2.26.1, 2.26.0, 2.25.0, 2.24.0, 2.23.0, 2.22.0, 2.21.0, 2.20.0, 2.19.1, 2.19.0, 2.18.0, 2.17.0, 2.16.0, 2.15.0, 2.14.1, 2.14.0, 2.13.0, 2.12.0, 2.11.0, 2.10.0, 2.9.0, 2.8.0, 2.7.0, 2.6.0, 2.5.0, 2.4.0, 2.3.0, 2.2.0, 2.1.0, 2.0.2, 1.12.11, 1.12.10, 1.12.8, 1.12.7, 1.12.6, 1.12.5, 1.12.4, 1.12.3, 1.12.2, 1.12.1, 1.12.0, 1.11.0, 1.10.1, 1.10.0, 1.9.3, 1.9.2, 1.9.1, 1.9.0, 1.8.4, 1.8.3, 1.8.2, 1.8.1, 1.8.0, 1.7.12, 1.7.11, 1.7.10, 1.7.9, 1.7.8, 1.7.7, 1.7.6, 1.7.5, 1.7.4, 1.7.3, 1.7.2, 1.7.1, 1.7.0, 1.6.7, 1.6.6, 1.6.5, 1.6.4, 1.6.3, 1.6.2, 1.6.1, 1.6.0, 1.5.5, 1.5.4, 1.5.3, 1.5.2, 1.5.1, 1.5.0, 1.4.2, 1.4.1, 1.4.0, 1.3.2, 1.3.1, 1.3, 1.2, 1.1, 1.0
    INSTALLED: 2.154.0
    LATEST:    2.156.0

-- Process STDERR
  WARNING: pip index is currently an experimental command. It may be removed/changed in a future release without prior warning.

Return code: SUCCESS (0)
```

### Relevant information

This has been the case for any package I view the installation options for, even though I can see that UniGetUI is detecting the versions internally through the logs.

### Screenshots and videos

![image](https://github.com/user-attachments/assets/be6d1c2d-1c4b-45e3-9432-e16618a27361)

**Comment by marticliment** [comment]
When updating a package, you can't change the install option, as the update command does not accept a version parameter. You should reinstall the package in order to get the option to change the version

**Comment by mrixner** [comment]
That makes sense. However, in trying to reinstall the program I uninstalled to test this (`appdirs`) the search feature wasn't coming back with any Pip results, and running the commands to search for the package came back with this error. Although, I feel like I've seen this error way prior than a day or so ago; has it always been like this? And if so, why is `parse_pip_search` suddenly failing to work?
Perhaps this is part of the problem referenced by #3079?

```
C:\Users\<username>\Projects\Windows\UniGetUI>C:\Users\<username>\AppData\Local\Programs\Python\Python312\Scripts\parse_pip_search.exe appdirs
 Package | Version | Description
---------------------------------

C:\Users\<username>\Projects\Windows\UniGetUI>pip search appdirs
ERROR: XMLRPC request failed [code: -32500]
RuntimeError: PyPI no longer supports 'pip search' (or XML-RPC search). Please use https://pypi.org/search (via a browser) instead. See https://warehouse.pypa.io/api-reference/xml-rpc.html#deprecated-methods for more information.
```

**Comment by marticliment** [comment]
Parse-pip-search seems to have broken. 
In fact, the original `pip-search` (https://pypi.org/project/pip-search/), from where I forked and created parse-pip-search, seems to not be working either.

```
C:\>pip_search pyside
   🐍 https://pypi.org/search/?q=pyside 🐍
┏━━━━━━━━━┳━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━━━━┓
┃ Package ┃ Version ┃ Released ┃ Description ┃
┡━━━━━━━━━╇━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━━━━┩
└─────────┴─────────┴──────────┴─────────────┘
```
