### ISSUE TITLE
Feature request 

### ISSUE THREAD

**Issue by considerate-mouth** [marticliment/UniGetUI#3105]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.1.4 

### Windows version, edition, and architecture

Win 11 Enterprise 26.100.2605 x64

### Describe your issue

![image](https://github.com/user-attachments/assets/56311aa5-6138-487f-a335-1501613563f4)

I want to be able to pull that bar up and down (marked in red) :)

### Steps to reproduce the issue

Just try and pull it. I assume you never made it a part of the UI, and you know it wont pull up and down with mouse.

(If I assume wrong sorry and will be back with logs and stuff)

### UniGetUI Log

```text
It's a feature request =)
```

### Package Managers Logs

```text
It's a feature request =)
```

**Comment by marticliment** [comment]
In fact, the PR https://github.com/marticliment/UniGetUI/pull/3070 is about this exact request, among others

**Comment by considerate-mouth** [comment]
> In fact, the PR #3070 is about this exact request, among others

Oh sorry I fucked up on that one
