### ISSUE TITLE
[BUG] hidden column

### ISSUE THREAD

**Issue by leminsc8er** [marticliment/UniGetUI#3133]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.1.5 portable

### Windows version, edition, and architecture

win 10

### Describe your issue

i have made the column with the scaling out menu of the source-filter-search mode so narrow that it has now disappeared.

### Steps to reproduce the issue
moving collume with mouse by softwareupdates on left side by ource-filter-search.

### Relevant information
Perhaps a “Reset display, function is useful for a start...”

**Comment by mrixner** [comment]
This is an intended feature; there is a filter button on the top right next to the search bar that will make it reappear.

**Comment by marticliment** [comment]
You can use this button:
![image](https://github.com/user-attachments/assets/1555e79f-9c3c-406b-9762-685573adbbc1)
