### ISSUE TITLE
[FEATURE REQUEST] A setting to only allow installation of signed packages

### ISSUE THREAD

**Issue by JaneX8** [marticliment/UniGetUI#3144]
### Please confirm these before moving forward.

- [X] I have searched for my feature proposal and have not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This proposal is a completely new feature. If you want to suggest an improvement or an enhancement, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=enhancement&projects=&template=enhancement-improvement.yml&title=%5BENHANCEMENT%5D+%28Enter+your+description+here%29).

### Describe the new feature

I would like a setting where I can enforce WinGetUI to only install binaries (so updates too) that contain a valid digital signature and prevent it from installing anything that does not have a valid digital signature.

### Describe how this new feature could help users

It would ensure origin authenticity and prevents unauthorized code execution.

**Comment by marticliment** [comment]
I am afraid this cannot be done, since the installation process is handled by the package managers themselves. Therefore, UniGetUI can't verify what is being installed.

**Comment by JaneX8** [comment]
But this can be done pre-installation I guess. At least for installers that are downloaded. The installer itself is signed or not and the signature can be verified before even starting the installer. 

So, after download but before running the installer.

**Comment by marticliment** [comment]
Yes, but UniGetUI does not have access to said downloaded files. When you tell unigetui to install X package, unigetui will spawn the command `winget install X` (assuming X is available from package manager winget), and will wait for it to finish. It is winget who downloads, checks and runs the installer itself.
