### ISSUE TITLE
[FEATURE REQUEST] Default Tab at Startup

### ISSUE THREAD

**Issue by hl2guide** [marticliment/UniGetUI#470]
## Before submitting the issue

- [x] **I have checked that the requested feature is not a duplicate or, if it is, it needs to be reopened**
- [x] **I have checked that I am running the latest version of WingetUI**
- [x] **I have checked the [FAQ](https://github.com/martinet101/WingetUI#faq) section**

## Is your feature request related to a problem? Please describe.

I'd like the default tab to be "Software Updates".

## Describe the solution you'd like

Please add a setting to set a default tab at startup.

**Comment by eidylon** [comment]
YES! Have a setting to select which tab should open by default when launching the app. 
- Discover Packages
- Software Updates
- Installed Packages

As a general rule, when I'm launching the UI, it's to go check for updates.

**Comment by marticliment** [comment]
Fixed on #2953 by @mrixner
