### ISSUE TITLE
[BUG/ISSUE] Tray icon not showing the search results for installed packaged and available updates

### ISSUE THREAD

**Issue by Mikey1993** [marticliment/UniGetUI#812]
## Before submitting the issue

- [X] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**
- [X] **I have checked that I am running the latest version of WingetUI**
- [X] **I have tried resetting and reinstalling WingetUI and the issue persisted or happened again**
- [X] **I have checked the [FAQ](https://github.com/martinet101/WingetUI#faq) section for solutions**
- [X] **I have read the [contributing guidelines](https://github.com/marticliment/WingetUI/blob/main/CONTRIBUTING.md#issues) and I agree with the [Code of Conduct](https://github.com/marticliment/WingetUI/blob/main/CODE_OF_CONDUCT.md)**

## Describe the bug
When having a search filter in the "Installed Packages" and/or "Software Updates" tabs, the tray icon lists are being filtered as well and show whatever the search results. which of course is not right and is not right as the tray icon shows different number of "XXX packages found" and "Available updates: X".
 
See the screenshots below for the filtered results (result that outputs an empty package list):
* "Installed Packages":
![image](https://user-images.githubusercontent.com/8223772/226145285-c9f0d1f3-ee44-4512-bd7d-cd88a8fb6923.png)
![image](https://user-images.githubusercontent.com/8223772/226145296-09caa8b0-022e-48a6-8c64-e28596185aa2.png)

* "Software Updates":
![image](https://user-images.githubusercontent.com/8223772/226145311-475c63f9-dec4-4c13-9364-5e9bae42cade.png)
![image](https://user-images.githubusercontent.com/8223772/226145348-1a8e8394-de47-41f3-b9b3-800487cd849a.png)

## To Reproduce
Steps to reproduce the behaviour:
1. Go to "Installed Packages" and/or "Software Updates" tabs
2. Search for something
3. Open tray icon and see the contents of the "XXX packages found" and "Available updates: X"
4. They are being filtered according to the search results which should not be.

## Expected behaviour
No filtering should be in place so that it won't be confusing, or either indicate that it's being filtered in some way in the tray icon.

**Comment by marticliment** [comment]
Actually, what I plan to do is to add the search box on the context menu as well, so context-menu filtering is also possible.

**Comment by marticliment** [comment]
This issue does not apply to WingetUI 3.0.0+/UniGetUI 3.1.0+
