### ISSUE TITLE
[CHOCO] view portable apps location 

### ISSUE THREAD

**Issue by Bazzu85** [marticliment/UniGetUI#959]
## Before submitting the issue

- [x] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**
- [x] **I have checked that I am running the latest version of WingetUI**
- [x] **I have checked that this issue is not an issue with the chocolatey utility, but rather with its implementation on WingetUI**
- [x] **I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions**
- [x] **I have read the [contributing guidelines](https://github.com/marticliment/WingetUI/blob/main/CONTRIBUTING.md#issues) and I agree with the [Code of Conduct](https://github.com/marticliment/WingetUI/blob/main/CODE_OF_CONDUCT.md)**

## Describe the issue
Hi,
Using the integrated choco.
I have installed baretail that's portable.
With chocolatey installed the portable apps are found in the programdata folder.
Using wingetui I can't find the folder where the app is..

**Comment by ppvnf** [comment]
what about having  a right click option in the uninstall section to open the install location? I think this could work for scoop packages as well
